// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

@class AuthRequest;
@class AuthRequest_Builder;
@class AuthResponse;
@class AuthResponse_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  AuthMethodImsi = 1,
  AuthMethodCtpassport = 2,
  AuthMethodMdn = 3,
  AuthMethodSurfingtoken = 4,
} AuthMethod;

BOOL AuthMethodIsValidValue(AuthMethod value);


@interface AuthProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface AuthRequest : ES_PBGeneratedMessage {
@private
  BOOL hasAccount_:1;
  BOOL hasPassword_:1;
  BOOL hasVerifySign_:1;
  BOOL hasMethod_:1;
  NSString* account;
  NSString* password;
  NSString* verifySign;
  AuthMethod method;
}
- (BOOL) hasMethod;
- (BOOL) hasAccount;
- (BOOL) hasPassword;
- (BOOL) hasVerifySign;
@property (readonly) AuthMethod method;
@property (readonly, retain) NSString* account;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* verifySign;

+ (AuthRequest*) defaultInstance;
- (AuthRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (AuthRequest_Builder*) builder;
+ (AuthRequest_Builder*) builder;
+ (AuthRequest_Builder*) builderWithPrototype:(AuthRequest*) prototype;
- (AuthRequest_Builder*) toBuilder;

+ (AuthRequest*) parseFromData:(NSData*) data;
+ (AuthRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (AuthRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AuthRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (AuthRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (AuthRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  AuthRequest* result;
}

- (AuthRequest*) defaultInstance;

- (AuthRequest_Builder*) clear;
- (AuthRequest_Builder*) clone;

- (AuthRequest*) build;
- (AuthRequest*) buildPartial;

- (AuthRequest_Builder*) mergeFrom:(AuthRequest*) other;
- (AuthRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (AuthRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMethod;
- (AuthMethod) method;
- (AuthRequest_Builder*) setMethod:(AuthMethod) value;
- (AuthRequest_Builder*) clearMethod;

- (BOOL) hasAccount;
- (NSString*) account;
- (AuthRequest_Builder*) setAccount:(NSString*) value;
- (AuthRequest_Builder*) clearAccount;

- (BOOL) hasPassword;
- (NSString*) password;
- (AuthRequest_Builder*) setPassword:(NSString*) value;
- (AuthRequest_Builder*) clearPassword;

- (BOOL) hasVerifySign;
- (NSString*) verifySign;
- (AuthRequest_Builder*) setVerifySign:(NSString*) value;
- (AuthRequest_Builder*) clearVerifySign;
@end

@interface AuthResponse : ES_PBGeneratedMessage {
@private
  BOOL hasSyncUserId_:1;
  BOOL hasToken_:1;
  BOOL hasPUserId_:1;
  BOOL hasMobileNum_:1;
  BOOL hasTokenExpires_:1;
  int64_t syncUserId;
  NSString* token;
  NSString* pUserId;
  NSString* mobileNum;
  uint32_t tokenExpires;
}
- (BOOL) hasToken;
- (BOOL) hasTokenExpires;
- (BOOL) hasPUserId;
- (BOOL) hasSyncUserId;
- (BOOL) hasMobileNum;
@property (readonly, retain) NSString* token;
@property (readonly) uint32_t tokenExpires;
@property (readonly, retain) NSString* pUserId;
@property (readonly) int64_t syncUserId;
@property (readonly, retain) NSString* mobileNum;

+ (AuthResponse*) defaultInstance;
- (AuthResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (AuthResponse_Builder*) builder;
+ (AuthResponse_Builder*) builder;
+ (AuthResponse_Builder*) builderWithPrototype:(AuthResponse*) prototype;
- (AuthResponse_Builder*) toBuilder;

+ (AuthResponse*) parseFromData:(NSData*) data;
+ (AuthResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (AuthResponse*) parseFromInputStream:(NSInputStream*) input;
+ (AuthResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (AuthResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (AuthResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  AuthResponse* result;
}

- (AuthResponse*) defaultInstance;

- (AuthResponse_Builder*) clear;
- (AuthResponse_Builder*) clone;

- (AuthResponse*) build;
- (AuthResponse*) buildPartial;

- (AuthResponse_Builder*) mergeFrom:(AuthResponse*) other;
- (AuthResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (AuthResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (AuthResponse_Builder*) setToken:(NSString*) value;
- (AuthResponse_Builder*) clearToken;

- (BOOL) hasTokenExpires;
- (uint32_t) tokenExpires;
- (AuthResponse_Builder*) setTokenExpires:(uint32_t) value;
- (AuthResponse_Builder*) clearTokenExpires;

- (BOOL) hasPUserId;
- (NSString*) pUserId;
- (AuthResponse_Builder*) setPUserId:(NSString*) value;
- (AuthResponse_Builder*) clearPUserId;

- (BOOL) hasSyncUserId;
- (int64_t) syncUserId;
- (AuthResponse_Builder*) setSyncUserId:(int64_t) value;
- (AuthResponse_Builder*) clearSyncUserId;

- (BOOL) hasMobileNum;
- (NSString*) mobileNum;
- (AuthResponse_Builder*) setMobileNum:(NSString*) value;
- (AuthResponse_Builder*) clearMobileNum;
@end

