// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

@class GetSysMsgRequest;
@class GetSysMsgRequest_Builder;
@class GetSysMsgResponse;
@class GetSysMsgResponse_Builder;
@class RequestSysMsg;
@class RequestSysMsg_Builder;
@class SysMsg;
@class SysMsg_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GetSysMsgProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface SysMsg : ES_PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasJobServerId_:1;
  BOOL hasDisplayType_:1;
  BOOL hasFrequency_:1;
  BOOL hasStartDate_:1;
  BOOL hasEndDate_:1;
  BOOL hasTitle_:1;
  BOOL hasContent_:1;
  int64_t timestamp;
  int32_t jobServerId;
  int32_t displayType;
  int32_t frequency;
  NSString* startDate;
  NSString* endDate;
  NSString* title;
  NSString* content;
}
- (BOOL) hasJobServerId;
- (BOOL) hasTimestamp;
- (BOOL) hasStartDate;
- (BOOL) hasEndDate;
- (BOOL) hasDisplayType;
- (BOOL) hasTitle;
- (BOOL) hasContent;
- (BOOL) hasFrequency;
@property (readonly) int32_t jobServerId;
@property (readonly) int64_t timestamp;
@property (readonly, retain) NSString* startDate;
@property (readonly, retain) NSString* endDate;
@property (readonly) int32_t displayType;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* content;
@property (readonly) int32_t frequency;

+ (SysMsg*) defaultInstance;
- (SysMsg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (SysMsg_Builder*) builder;
+ (SysMsg_Builder*) builder;
+ (SysMsg_Builder*) builderWithPrototype:(SysMsg*) prototype;
- (SysMsg_Builder*) toBuilder;

+ (SysMsg*) parseFromData:(NSData*) data;
+ (SysMsg*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (SysMsg*) parseFromInputStream:(NSInputStream*) input;
+ (SysMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (SysMsg*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (SysMsg*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface SysMsg_Builder : ES_PBGeneratedMessage_Builder {
@private
  SysMsg* result;
}

- (SysMsg*) defaultInstance;

- (SysMsg_Builder*) clear;
- (SysMsg_Builder*) clone;

- (SysMsg*) build;
- (SysMsg*) buildPartial;

- (SysMsg_Builder*) mergeFrom:(SysMsg*) other;
- (SysMsg_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (SysMsg_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasJobServerId;
- (int32_t) jobServerId;
- (SysMsg_Builder*) setJobServerId:(int32_t) value;
- (SysMsg_Builder*) clearJobServerId;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (SysMsg_Builder*) setTimestamp:(int64_t) value;
- (SysMsg_Builder*) clearTimestamp;

- (BOOL) hasStartDate;
- (NSString*) startDate;
- (SysMsg_Builder*) setStartDate:(NSString*) value;
- (SysMsg_Builder*) clearStartDate;

- (BOOL) hasEndDate;
- (NSString*) endDate;
- (SysMsg_Builder*) setEndDate:(NSString*) value;
- (SysMsg_Builder*) clearEndDate;

- (BOOL) hasDisplayType;
- (int32_t) displayType;
- (SysMsg_Builder*) setDisplayType:(int32_t) value;
- (SysMsg_Builder*) clearDisplayType;

- (BOOL) hasTitle;
- (NSString*) title;
- (SysMsg_Builder*) setTitle:(NSString*) value;
- (SysMsg_Builder*) clearTitle;

- (BOOL) hasContent;
- (NSString*) content;
- (SysMsg_Builder*) setContent:(NSString*) value;
- (SysMsg_Builder*) clearContent;

- (BOOL) hasFrequency;
- (int32_t) frequency;
- (SysMsg_Builder*) setFrequency:(int32_t) value;
- (SysMsg_Builder*) clearFrequency;
@end

@interface RequestSysMsg : ES_PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasJobServerId_:1;
  int64_t timestamp;
  int32_t jobServerId;
}
- (BOOL) hasJobServerId;
- (BOOL) hasTimestamp;
@property (readonly) int32_t jobServerId;
@property (readonly) int64_t timestamp;

+ (RequestSysMsg*) defaultInstance;
- (RequestSysMsg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (RequestSysMsg_Builder*) builder;
+ (RequestSysMsg_Builder*) builder;
+ (RequestSysMsg_Builder*) builderWithPrototype:(RequestSysMsg*) prototype;
- (RequestSysMsg_Builder*) toBuilder;

+ (RequestSysMsg*) parseFromData:(NSData*) data;
+ (RequestSysMsg*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (RequestSysMsg*) parseFromInputStream:(NSInputStream*) input;
+ (RequestSysMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (RequestSysMsg*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (RequestSysMsg*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface RequestSysMsg_Builder : ES_PBGeneratedMessage_Builder {
@private
  RequestSysMsg* result;
}

- (RequestSysMsg*) defaultInstance;

- (RequestSysMsg_Builder*) clear;
- (RequestSysMsg_Builder*) clone;

- (RequestSysMsg*) build;
- (RequestSysMsg*) buildPartial;

- (RequestSysMsg_Builder*) mergeFrom:(RequestSysMsg*) other;
- (RequestSysMsg_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (RequestSysMsg_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasJobServerId;
- (int32_t) jobServerId;
- (RequestSysMsg_Builder*) setJobServerId:(int32_t) value;
- (RequestSysMsg_Builder*) clearJobServerId;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (RequestSysMsg_Builder*) setTimestamp:(int64_t) value;
- (RequestSysMsg_Builder*) clearTimestamp;
@end

@interface GetSysMsgRequest : ES_PBGeneratedMessage {
@private
  BOOL hasMobileNum_:1;
  BOOL hasImsi_:1;
  BOOL hasMobileManufacturer_:1;
  BOOL hasMobileType_:1;
  NSString* mobileNum;
  NSString* imsi;
  NSString* mobileManufacturer;
  NSString* mobileType;
  ES_PBAppendableArray * messagesArray;
}
- (BOOL) hasMobileNum;
- (BOOL) hasImsi;
- (BOOL) hasMobileManufacturer;
- (BOOL) hasMobileType;
@property (readonly, retain) NSString* mobileNum;
@property (readonly, retain) NSString* imsi;
@property (readonly, retain) NSString* mobileManufacturer;
@property (readonly, retain) NSString* mobileType;
@property (readonly, retain) ES_PBArray * messages;
- (RequestSysMsg*)messagesAtIndex:(NSUInteger)index;

+ (GetSysMsgRequest*) defaultInstance;
- (GetSysMsgRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (GetSysMsgRequest_Builder*) builder;
+ (GetSysMsgRequest_Builder*) builder;
+ (GetSysMsgRequest_Builder*) builderWithPrototype:(GetSysMsgRequest*) prototype;
- (GetSysMsgRequest_Builder*) toBuilder;

+ (GetSysMsgRequest*) parseFromData:(NSData*) data;
+ (GetSysMsgRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSysMsgRequest*) parseFromInputStream:(NSInputStream*) input;
+ (GetSysMsgRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSysMsgRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (GetSysMsgRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface GetSysMsgRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  GetSysMsgRequest* result;
}

- (GetSysMsgRequest*) defaultInstance;

- (GetSysMsgRequest_Builder*) clear;
- (GetSysMsgRequest_Builder*) clone;

- (GetSysMsgRequest*) build;
- (GetSysMsgRequest*) buildPartial;

- (GetSysMsgRequest_Builder*) mergeFrom:(GetSysMsgRequest*) other;
- (GetSysMsgRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (GetSysMsgRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMobileNum;
- (NSString*) mobileNum;
- (GetSysMsgRequest_Builder*) setMobileNum:(NSString*) value;
- (GetSysMsgRequest_Builder*) clearMobileNum;

- (BOOL) hasImsi;
- (NSString*) imsi;
- (GetSysMsgRequest_Builder*) setImsi:(NSString*) value;
- (GetSysMsgRequest_Builder*) clearImsi;

- (BOOL) hasMobileManufacturer;
- (NSString*) mobileManufacturer;
- (GetSysMsgRequest_Builder*) setMobileManufacturer:(NSString*) value;
- (GetSysMsgRequest_Builder*) clearMobileManufacturer;

- (BOOL) hasMobileType;
- (NSString*) mobileType;
- (GetSysMsgRequest_Builder*) setMobileType:(NSString*) value;
- (GetSysMsgRequest_Builder*) clearMobileType;

- (ES_PBAppendableArray *)messages;
- (RequestSysMsg*)messagesAtIndex:(NSUInteger)index;
- (GetSysMsgRequest_Builder *)addMessages:(RequestSysMsg*)value;
- (GetSysMsgRequest_Builder *)setMessagesArray:(NSArray *)array;
- (GetSysMsgRequest_Builder *)setMessagesValues:(const RequestSysMsg* *)values count:(NSUInteger)count;
- (GetSysMsgRequest_Builder *)clearMessages;
@end

@interface GetSysMsgResponse : ES_PBGeneratedMessage {
@private
  BOOL hasFrequency_:1;
  int32_t frequency;
  ES_PBAppendableArray * messagesArray;
}
- (BOOL) hasFrequency;
@property (readonly, retain) ES_PBArray * messages;
@property (readonly) int32_t frequency;
- (SysMsg*)messagesAtIndex:(NSUInteger)index;

+ (GetSysMsgResponse*) defaultInstance;
- (GetSysMsgResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (GetSysMsgResponse_Builder*) builder;
+ (GetSysMsgResponse_Builder*) builder;
+ (GetSysMsgResponse_Builder*) builderWithPrototype:(GetSysMsgResponse*) prototype;
- (GetSysMsgResponse_Builder*) toBuilder;

+ (GetSysMsgResponse*) parseFromData:(NSData*) data;
+ (GetSysMsgResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSysMsgResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetSysMsgResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSysMsgResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (GetSysMsgResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface GetSysMsgResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  GetSysMsgResponse* result;
}

- (GetSysMsgResponse*) defaultInstance;

- (GetSysMsgResponse_Builder*) clear;
- (GetSysMsgResponse_Builder*) clone;

- (GetSysMsgResponse*) build;
- (GetSysMsgResponse*) buildPartial;

- (GetSysMsgResponse_Builder*) mergeFrom:(GetSysMsgResponse*) other;
- (GetSysMsgResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (GetSysMsgResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (ES_PBAppendableArray *)messages;
- (SysMsg*)messagesAtIndex:(NSUInteger)index;
- (GetSysMsgResponse_Builder *)addMessages:(SysMsg*)value;
- (GetSysMsgResponse_Builder *)setMessagesArray:(NSArray *)array;
- (GetSysMsgResponse_Builder *)setMessagesValues:(const SysMsg* *)values count:(NSUInteger)count;
- (GetSysMsgResponse_Builder *)clearMessages;

- (BOOL) hasFrequency;
- (int32_t) frequency;
- (GetSysMsgResponse_Builder*) setFrequency:(int32_t) value;
- (GetSysMsgResponse_Builder*) clearFrequency;
@end

