// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Download_sms_proto.pb.h"

@implementation DownloadSmsProtoRoot
static ES_PBExtensionRegistry* extensionRegistry = nil;
+ (ES_PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [DownloadSmsProtoRoot class]) {
    ES_PBMutableExtensionRegistry* registry = [ES_PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [BaseTypeProtoRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry {
}
@end

@interface DownloadSmsRequest ()
@property (retain) ES_PBAppendableArray * idArray;
@end

@implementation DownloadSmsRequest

@synthesize idArray;
@dynamic id;
- (void) dealloc {
  self.idArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static DownloadSmsRequest* defaultDownloadSmsRequestInstance = nil;
+ (void) initialize {
  if (self == [DownloadSmsRequest class]) {
    defaultDownloadSmsRequestInstance = [[DownloadSmsRequest alloc] init];
  }
}
+ (DownloadSmsRequest*) defaultInstance {
  return defaultDownloadSmsRequestInstance;
}
- (DownloadSmsRequest*) defaultInstance {
  return defaultDownloadSmsRequestInstance;
}
- (ES_PBArray *)id {
  return idArray;
}
- (NSString*)idAtIndex:(NSUInteger)index {
  return [idArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output {
  const NSUInteger idArrayCount = self.idArray.count;
  if (idArrayCount > 0) {
    const NSString* *values = (const NSString* *)self.idArray.data;
    for (NSUInteger i = 0; i < idArrayCount; ++i) {
      [output writeString:1 value:values[i]];
    }
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  {
    int32_t dataSize = 0;
    const NSUInteger count = self.idArray.count;
    const NSString* *values = (const NSString* *)self.idArray.data;
    for (NSUInteger i = 0; i < count; ++i) {
      dataSize += ES_computeStringSizeNoTag(values[i]);
    }
    size_ += dataSize;
    size_ += 1 * count;
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (DownloadSmsRequest*) parseFromData:(NSData*) data {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromData:data] build];
}
+ (DownloadSmsRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsRequest*) parseFromInputStream:(NSInputStream*) input {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromInputStream:input] build];
}
+ (DownloadSmsRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromCodedInputStream:input] build];
}
+ (DownloadSmsRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsRequest_Builder*) builder {
  return [[[DownloadSmsRequest_Builder alloc] init] autorelease];
}
+ (DownloadSmsRequest_Builder*) builderWithPrototype:(DownloadSmsRequest*) prototype {
  return [[DownloadSmsRequest builder] mergeFrom:prototype];
}
- (DownloadSmsRequest_Builder*) builder {
  return [DownloadSmsRequest builder];
}
- (DownloadSmsRequest_Builder*) toBuilder {
  return [DownloadSmsRequest builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  for (NSString* element in self.idArray) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", element];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[DownloadSmsRequest class]]) {
    return NO;
  }
  DownloadSmsRequest *otherMessage = other;
  return
      [self.idArray isEqualToArray:otherMessage.idArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  for (NSString* element in self.idArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface DownloadSmsRequest_Builder()
@property (retain) DownloadSmsRequest* result;
@end

@implementation DownloadSmsRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DownloadSmsRequest alloc] init] autorelease];
  }
  return self;
}
- (ES_PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DownloadSmsRequest_Builder*) clear {
  self.result = [[[DownloadSmsRequest alloc] init] autorelease];
  return self;
}
- (DownloadSmsRequest_Builder*) clone {
  return [DownloadSmsRequest builderWithPrototype:result];
}
- (DownloadSmsRequest*) defaultInstance {
  return [DownloadSmsRequest defaultInstance];
}
- (DownloadSmsRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DownloadSmsRequest*) buildPartial {
  DownloadSmsRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DownloadSmsRequest_Builder*) mergeFrom:(DownloadSmsRequest*) other {
  if (other == [DownloadSmsRequest defaultInstance]) {
    return self;
  }
  if (other.idArray.count > 0) {
    if (result.idArray == nil) {
      result.idArray = [[other.idArray copyWithZone:[other.idArray zone]] autorelease];
    } else {
      [result.idArray appendArray:other.idArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DownloadSmsRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[ES_PBExtensionRegistry emptyRegistry]];
}
- (DownloadSmsRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  ES_PBUnknownFieldSet_Builder* unknownFields = [ES_PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self addId:[input readString]];
        break;
      }
    }
  }
}
- (ES_PBAppendableArray *)id {
  return result.idArray;
}
- (NSString*)idAtIndex:(NSUInteger)index {
  return [result idAtIndex:index];
}
- (DownloadSmsRequest_Builder *)addId:(NSString*)value {
  if (result.idArray == nil) {
    result.idArray = [ES_PBAppendableArray arrayWithValueType:ES_PBArrayValueTypeObject];
  }
  [result.idArray addObject:value];
  return self;
}
- (DownloadSmsRequest_Builder *)setIdArray:(NSArray *)array {
  result.idArray = [ES_PBAppendableArray arrayWithArray:array valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (DownloadSmsRequest_Builder *)setIdValues:(const NSString* *)values count:(NSUInteger)count {
  result.idArray = [ES_PBAppendableArray arrayWithValues:values count:count valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (DownloadSmsRequest_Builder *)clearId {
  result.idArray = nil;
  return self;
}
@end

@interface DownloadSmsResponse ()
@property (retain) ES_PBAppendableArray * smsArray;
@end

@implementation DownloadSmsResponse

@synthesize smsArray;
@dynamic sms;
- (void) dealloc {
  self.smsArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static DownloadSmsResponse* defaultDownloadSmsResponseInstance = nil;
+ (void) initialize {
  if (self == [DownloadSmsResponse class]) {
    defaultDownloadSmsResponseInstance = [[DownloadSmsResponse alloc] init];
  }
}
+ (DownloadSmsResponse*) defaultInstance {
  return defaultDownloadSmsResponseInstance;
}
- (DownloadSmsResponse*) defaultInstance {
  return defaultDownloadSmsResponseInstance;
}
- (ES_PBArray *)sms {
  return smsArray;
}
- (Sms*)smsAtIndex:(NSUInteger)index {
  return [smsArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  for (Sms* element in self.sms) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output {
  for (Sms *element in self.smsArray) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  for (Sms *element in self.smsArray) {
    size_ += ES_computeMessageSize(1, element);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (DownloadSmsResponse*) parseFromData:(NSData*) data {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromData:data] build];
}
+ (DownloadSmsResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsResponse*) parseFromInputStream:(NSInputStream*) input {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromInputStream:input] build];
}
+ (DownloadSmsResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromCodedInputStream:input] build];
}
+ (DownloadSmsResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsResponse_Builder*) builder {
  return [[[DownloadSmsResponse_Builder alloc] init] autorelease];
}
+ (DownloadSmsResponse_Builder*) builderWithPrototype:(DownloadSmsResponse*) prototype {
  return [[DownloadSmsResponse builder] mergeFrom:prototype];
}
- (DownloadSmsResponse_Builder*) builder {
  return [DownloadSmsResponse builder];
}
- (DownloadSmsResponse_Builder*) toBuilder {
  return [DownloadSmsResponse builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  for (Sms* element in self.smsArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"sms"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[DownloadSmsResponse class]]) {
    return NO;
  }
  DownloadSmsResponse *otherMessage = other;
  return
      [self.smsArray isEqualToArray:otherMessage.smsArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  for (Sms* element in self.smsArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface DownloadSmsResponse_Builder()
@property (retain) DownloadSmsResponse* result;
@end

@implementation DownloadSmsResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DownloadSmsResponse alloc] init] autorelease];
  }
  return self;
}
- (ES_PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DownloadSmsResponse_Builder*) clear {
  self.result = [[[DownloadSmsResponse alloc] init] autorelease];
  return self;
}
- (DownloadSmsResponse_Builder*) clone {
  return [DownloadSmsResponse builderWithPrototype:result];
}
- (DownloadSmsResponse*) defaultInstance {
  return [DownloadSmsResponse defaultInstance];
}
- (DownloadSmsResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DownloadSmsResponse*) buildPartial {
  DownloadSmsResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DownloadSmsResponse_Builder*) mergeFrom:(DownloadSmsResponse*) other {
  if (other == [DownloadSmsResponse defaultInstance]) {
    return self;
  }
  if (other.smsArray.count > 0) {
    if (result.smsArray == nil) {
      result.smsArray = [[other.smsArray copyWithZone:[other.smsArray zone]] autorelease];
    } else {
      [result.smsArray appendArray:other.smsArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DownloadSmsResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[ES_PBExtensionRegistry emptyRegistry]];
}
- (DownloadSmsResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  ES_PBUnknownFieldSet_Builder* unknownFields = [ES_PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        Sms_Builder* subBuilder = [Sms builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addSms:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (ES_PBAppendableArray *)sms {
  return result.smsArray;
}
- (Sms*)smsAtIndex:(NSUInteger)index {
  return [result smsAtIndex:index];
}
- (DownloadSmsResponse_Builder *)addSms:(Sms*)value {
  if (result.smsArray == nil) {
    result.smsArray = [ES_PBAppendableArray arrayWithValueType:ES_PBArrayValueTypeObject];
  }
  [result.smsArray addObject:value];
  return self;
}
- (DownloadSmsResponse_Builder *)setSmsArray:(NSArray *)array {
  result.smsArray = [ES_PBAppendableArray arrayWithArray:array valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (DownloadSmsResponse_Builder *)setSmsValues:(const Sms* *)values count:(NSUInteger)count {
  result.smsArray = [ES_PBAppendableArray arrayWithValues:values count:count valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (DownloadSmsResponse_Builder *)clearSms {
  result.smsArray = nil;
  return self;
}
@end

