// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

@class GetSplashRequest;
@class GetSplashRequest_Builder;
@class GetSplashResponse;
@class GetSplashResponse_Builder;
@class Splash;
@class Splash_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GetSplashProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface Splash : ES_PBGeneratedMessage {
@private
  BOOL hasUrl_:1;
  BOOL hasImageType_:1;
  BOOL hasData_:1;
  NSString* url;
  NSString* imageType;
  NSData* data;
}
- (BOOL) hasData;
- (BOOL) hasUrl;
- (BOOL) hasImageType;
@property (readonly, retain) NSData* data;
@property (readonly, retain) NSString* url;
@property (readonly, retain) NSString* imageType;

+ (Splash*) defaultInstance;
- (Splash*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (Splash_Builder*) builder;
+ (Splash_Builder*) builder;
+ (Splash_Builder*) builderWithPrototype:(Splash*) prototype;
- (Splash_Builder*) toBuilder;

+ (Splash*) parseFromData:(NSData*) data;
+ (Splash*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (Splash*) parseFromInputStream:(NSInputStream*) input;
+ (Splash*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (Splash*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (Splash*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface Splash_Builder : ES_PBGeneratedMessage_Builder {
@private
  Splash* result;
}

- (Splash*) defaultInstance;

- (Splash_Builder*) clear;
- (Splash_Builder*) clone;

- (Splash*) build;
- (Splash*) buildPartial;

- (Splash_Builder*) mergeFrom:(Splash*) other;
- (Splash_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (Splash_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasData;
- (NSData*) data;
- (Splash_Builder*) setData:(NSData*) value;
- (Splash_Builder*) clearData;

- (BOOL) hasUrl;
- (NSString*) url;
- (Splash_Builder*) setUrl:(NSString*) value;
- (Splash_Builder*) clearUrl;

- (BOOL) hasImageType;
- (NSString*) imageType;
- (Splash_Builder*) setImageType:(NSString*) value;
- (Splash_Builder*) clearImageType;
@end

@interface GetSplashRequest : ES_PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasJobServerId_:1;
  BOOL hasScreenWidth_:1;
  BOOL hasScreenHeight_:1;
  BOOL hasMobileNum_:1;
  BOOL hasImsi_:1;
  BOOL hasMobileManufacturer_:1;
  BOOL hasMobileType_:1;
  int64_t timestamp;
  int32_t jobServerId;
  int32_t screenWidth;
  int32_t screenHeight;
  NSString* mobileNum;
  NSString* imsi;
  NSString* mobileManufacturer;
  NSString* mobileType;
}
- (BOOL) hasMobileNum;
- (BOOL) hasImsi;
- (BOOL) hasMobileManufacturer;
- (BOOL) hasMobileType;
- (BOOL) hasJobServerId;
- (BOOL) hasTimestamp;
- (BOOL) hasScreenWidth;
- (BOOL) hasScreenHeight;
@property (readonly, retain) NSString* mobileNum;
@property (readonly, retain) NSString* imsi;
@property (readonly, retain) NSString* mobileManufacturer;
@property (readonly, retain) NSString* mobileType;
@property (readonly) int32_t jobServerId;
@property (readonly) int64_t timestamp;
@property (readonly) int32_t screenWidth;
@property (readonly) int32_t screenHeight;

+ (GetSplashRequest*) defaultInstance;
- (GetSplashRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (GetSplashRequest_Builder*) builder;
+ (GetSplashRequest_Builder*) builder;
+ (GetSplashRequest_Builder*) builderWithPrototype:(GetSplashRequest*) prototype;
- (GetSplashRequest_Builder*) toBuilder;

+ (GetSplashRequest*) parseFromData:(NSData*) data;
+ (GetSplashRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSplashRequest*) parseFromInputStream:(NSInputStream*) input;
+ (GetSplashRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSplashRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (GetSplashRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface GetSplashRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  GetSplashRequest* result;
}

- (GetSplashRequest*) defaultInstance;

- (GetSplashRequest_Builder*) clear;
- (GetSplashRequest_Builder*) clone;

- (GetSplashRequest*) build;
- (GetSplashRequest*) buildPartial;

- (GetSplashRequest_Builder*) mergeFrom:(GetSplashRequest*) other;
- (GetSplashRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (GetSplashRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMobileNum;
- (NSString*) mobileNum;
- (GetSplashRequest_Builder*) setMobileNum:(NSString*) value;
- (GetSplashRequest_Builder*) clearMobileNum;

- (BOOL) hasImsi;
- (NSString*) imsi;
- (GetSplashRequest_Builder*) setImsi:(NSString*) value;
- (GetSplashRequest_Builder*) clearImsi;

- (BOOL) hasMobileManufacturer;
- (NSString*) mobileManufacturer;
- (GetSplashRequest_Builder*) setMobileManufacturer:(NSString*) value;
- (GetSplashRequest_Builder*) clearMobileManufacturer;

- (BOOL) hasMobileType;
- (NSString*) mobileType;
- (GetSplashRequest_Builder*) setMobileType:(NSString*) value;
- (GetSplashRequest_Builder*) clearMobileType;

- (BOOL) hasJobServerId;
- (int32_t) jobServerId;
- (GetSplashRequest_Builder*) setJobServerId:(int32_t) value;
- (GetSplashRequest_Builder*) clearJobServerId;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (GetSplashRequest_Builder*) setTimestamp:(int64_t) value;
- (GetSplashRequest_Builder*) clearTimestamp;

- (BOOL) hasScreenWidth;
- (int32_t) screenWidth;
- (GetSplashRequest_Builder*) setScreenWidth:(int32_t) value;
- (GetSplashRequest_Builder*) clearScreenWidth;

- (BOOL) hasScreenHeight;
- (int32_t) screenHeight;
- (GetSplashRequest_Builder*) setScreenHeight:(int32_t) value;
- (GetSplashRequest_Builder*) clearScreenHeight;
@end

@interface GetSplashResponse : ES_PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasJobServerId_:1;
  BOOL hasDisplayTime_:1;
  BOOL hasFrequency_:1;
  BOOL hasStartDate_:1;
  BOOL hasEndDate_:1;
  BOOL hasBackgroundColor_:1;
  int64_t timestamp;
  int32_t jobServerId;
  int32_t displayTime;
  int32_t frequency;
  NSString* startDate;
  NSString* endDate;
  NSString* backgroundColor;
  ES_PBAppendableArray * splashArray;
}
- (BOOL) hasJobServerId;
- (BOOL) hasTimestamp;
- (BOOL) hasStartDate;
- (BOOL) hasEndDate;
- (BOOL) hasBackgroundColor;
- (BOOL) hasDisplayTime;
- (BOOL) hasFrequency;
@property (readonly) int32_t jobServerId;
@property (readonly) int64_t timestamp;
@property (readonly, retain) NSString* startDate;
@property (readonly, retain) NSString* endDate;
@property (readonly, retain) NSString* backgroundColor;
@property (readonly) int32_t displayTime;
@property (readonly, retain) ES_PBArray * splash;
@property (readonly) int32_t frequency;
- (Splash*)splashAtIndex:(NSUInteger)index;

+ (GetSplashResponse*) defaultInstance;
- (GetSplashResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (GetSplashResponse_Builder*) builder;
+ (GetSplashResponse_Builder*) builder;
+ (GetSplashResponse_Builder*) builderWithPrototype:(GetSplashResponse*) prototype;
- (GetSplashResponse_Builder*) toBuilder;

+ (GetSplashResponse*) parseFromData:(NSData*) data;
+ (GetSplashResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSplashResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetSplashResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetSplashResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (GetSplashResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface GetSplashResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  GetSplashResponse* result;
}

- (GetSplashResponse*) defaultInstance;

- (GetSplashResponse_Builder*) clear;
- (GetSplashResponse_Builder*) clone;

- (GetSplashResponse*) build;
- (GetSplashResponse*) buildPartial;

- (GetSplashResponse_Builder*) mergeFrom:(GetSplashResponse*) other;
- (GetSplashResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (GetSplashResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasJobServerId;
- (int32_t) jobServerId;
- (GetSplashResponse_Builder*) setJobServerId:(int32_t) value;
- (GetSplashResponse_Builder*) clearJobServerId;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (GetSplashResponse_Builder*) setTimestamp:(int64_t) value;
- (GetSplashResponse_Builder*) clearTimestamp;

- (BOOL) hasStartDate;
- (NSString*) startDate;
- (GetSplashResponse_Builder*) setStartDate:(NSString*) value;
- (GetSplashResponse_Builder*) clearStartDate;

- (BOOL) hasEndDate;
- (NSString*) endDate;
- (GetSplashResponse_Builder*) setEndDate:(NSString*) value;
- (GetSplashResponse_Builder*) clearEndDate;

- (BOOL) hasBackgroundColor;
- (NSString*) backgroundColor;
- (GetSplashResponse_Builder*) setBackgroundColor:(NSString*) value;
- (GetSplashResponse_Builder*) clearBackgroundColor;

- (BOOL) hasDisplayTime;
- (int32_t) displayTime;
- (GetSplashResponse_Builder*) setDisplayTime:(int32_t) value;
- (GetSplashResponse_Builder*) clearDisplayTime;

- (ES_PBAppendableArray *)splash;
- (Splash*)splashAtIndex:(NSUInteger)index;
- (GetSplashResponse_Builder *)addSplash:(Splash*)value;
- (GetSplashResponse_Builder *)setSplashArray:(NSArray *)array;
- (GetSplashResponse_Builder *)setSplashValues:(const Splash* *)values count:(NSUInteger)count;
- (GetSplashResponse_Builder *)clearSplash;

- (BOOL) hasFrequency;
- (int32_t) frequency;
- (GetSplashResponse_Builder*) setFrequency:(int32_t) value;
- (GetSplashResponse_Builder*) clearFrequency;
@end

