// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Get_config_proto.pb.h"

@implementation GetConfigProtoRoot
static ES_PBExtensionRegistry* extensionRegistry = nil;
+ (ES_PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [GetConfigProtoRoot class]) {
    ES_PBMutableExtensionRegistry* registry = [ES_PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry {
}
@end

@interface GetConfigResponse ()
@property uint32_t sessionExpires;
@property (retain) NSString* authUrl;
@property int32_t tpnoolVersion;
@property (retain) NSString* tpnoolUrl;
@property (retain) NSString* uploadPortraitUrl;
@property (retain) NSString* downloadPortraitUrl;
@property (retain) NSString* uploadAllUrl;
@property (retain) NSString* getContactListUrl;
@property (retain) NSString* downloadContactUrl;
@property (retain) NSString* syncUploadContactUrl;
@property (retain) NSString* getContactListVersionUrl;
@property (retain) NSString* slowSyncUrl;
@property (retain) NSString* syncPortraitUrl;
@property (retain) NSString* syncSmsUrl;
@property (retain) NSString* uploadSmsUrl;
@property (retain) NSString* downloadSmsUrl;
@property (retain) NSString* clientReportUrl;
@property (retain) NSString* backupCalllogUrl;
@property (retain) NSString* recoverCalllogUrl;
@property (retain) NSString* storageHostUrl;
@property (retain) NSString* deviceSignUrl;
@property (retain) NSString* plainClientReportUrl;
@property (retain) NSString* downloadAllUrl;
@property (retain) NSString* getUserCloudSummaryUrl;
@property (retain) NSString* queryClientVersionUrl;
@property (retain) NSString* queryMobileNoUrl;
@property (retain) NSString* getSplashUrl;
@property (retain) NSString* getSysMsgUrl;
@property (retain) NSString* queryPublicInfoUrl;
@property (retain) NSString* queryCommentsUrl;
@property (retain) NSString* uploadAllUrlV2;
@end

@implementation GetConfigResponse

- (BOOL) hasSessionExpires {
  return !!hasSessionExpires_;
}
- (void) setHasSessionExpires:(BOOL) value_ {
  hasSessionExpires_ = !!value_;
}
@synthesize sessionExpires;
- (BOOL) hasAuthUrl {
  return !!hasAuthUrl_;
}
- (void) setHasAuthUrl:(BOOL) value_ {
  hasAuthUrl_ = !!value_;
}
@synthesize authUrl;
- (BOOL) hasTpnoolVersion {
  return !!hasTpnoolVersion_;
}
- (void) setHasTpnoolVersion:(BOOL) value_ {
  hasTpnoolVersion_ = !!value_;
}
@synthesize tpnoolVersion;
- (BOOL) hasTpnoolUrl {
  return !!hasTpnoolUrl_;
}
- (void) setHasTpnoolUrl:(BOOL) value_ {
  hasTpnoolUrl_ = !!value_;
}
@synthesize tpnoolUrl;
- (BOOL) hasUploadPortraitUrl {
  return !!hasUploadPortraitUrl_;
}
- (void) setHasUploadPortraitUrl:(BOOL) value_ {
  hasUploadPortraitUrl_ = !!value_;
}
@synthesize uploadPortraitUrl;
- (BOOL) hasDownloadPortraitUrl {
  return !!hasDownloadPortraitUrl_;
}
- (void) setHasDownloadPortraitUrl:(BOOL) value_ {
  hasDownloadPortraitUrl_ = !!value_;
}
@synthesize downloadPortraitUrl;
- (BOOL) hasUploadAllUrl {
  return !!hasUploadAllUrl_;
}
- (void) setHasUploadAllUrl:(BOOL) value_ {
  hasUploadAllUrl_ = !!value_;
}
@synthesize uploadAllUrl;
- (BOOL) hasGetContactListUrl {
  return !!hasGetContactListUrl_;
}
- (void) setHasGetContactListUrl:(BOOL) value_ {
  hasGetContactListUrl_ = !!value_;
}
@synthesize getContactListUrl;
- (BOOL) hasDownloadContactUrl {
  return !!hasDownloadContactUrl_;
}
- (void) setHasDownloadContactUrl:(BOOL) value_ {
  hasDownloadContactUrl_ = !!value_;
}
@synthesize downloadContactUrl;
- (BOOL) hasSyncUploadContactUrl {
  return !!hasSyncUploadContactUrl_;
}
- (void) setHasSyncUploadContactUrl:(BOOL) value_ {
  hasSyncUploadContactUrl_ = !!value_;
}
@synthesize syncUploadContactUrl;
- (BOOL) hasGetContactListVersionUrl {
  return !!hasGetContactListVersionUrl_;
}
- (void) setHasGetContactListVersionUrl:(BOOL) value_ {
  hasGetContactListVersionUrl_ = !!value_;
}
@synthesize getContactListVersionUrl;
- (BOOL) hasSlowSyncUrl {
  return !!hasSlowSyncUrl_;
}
- (void) setHasSlowSyncUrl:(BOOL) value_ {
  hasSlowSyncUrl_ = !!value_;
}
@synthesize slowSyncUrl;
- (BOOL) hasSyncPortraitUrl {
  return !!hasSyncPortraitUrl_;
}
- (void) setHasSyncPortraitUrl:(BOOL) value_ {
  hasSyncPortraitUrl_ = !!value_;
}
@synthesize syncPortraitUrl;
- (BOOL) hasSyncSmsUrl {
  return !!hasSyncSmsUrl_;
}
- (void) setHasSyncSmsUrl:(BOOL) value_ {
  hasSyncSmsUrl_ = !!value_;
}
@synthesize syncSmsUrl;
- (BOOL) hasUploadSmsUrl {
  return !!hasUploadSmsUrl_;
}
- (void) setHasUploadSmsUrl:(BOOL) value_ {
  hasUploadSmsUrl_ = !!value_;
}
@synthesize uploadSmsUrl;
- (BOOL) hasDownloadSmsUrl {
  return !!hasDownloadSmsUrl_;
}
- (void) setHasDownloadSmsUrl:(BOOL) value_ {
  hasDownloadSmsUrl_ = !!value_;
}
@synthesize downloadSmsUrl;
- (BOOL) hasClientReportUrl {
  return !!hasClientReportUrl_;
}
- (void) setHasClientReportUrl:(BOOL) value_ {
  hasClientReportUrl_ = !!value_;
}
@synthesize clientReportUrl;
- (BOOL) hasBackupCalllogUrl {
  return !!hasBackupCalllogUrl_;
}
- (void) setHasBackupCalllogUrl:(BOOL) value_ {
  hasBackupCalllogUrl_ = !!value_;
}
@synthesize backupCalllogUrl;
- (BOOL) hasRecoverCalllogUrl {
  return !!hasRecoverCalllogUrl_;
}
- (void) setHasRecoverCalllogUrl:(BOOL) value_ {
  hasRecoverCalllogUrl_ = !!value_;
}
@synthesize recoverCalllogUrl;
- (BOOL) hasStorageHostUrl {
  return !!hasStorageHostUrl_;
}
- (void) setHasStorageHostUrl:(BOOL) value_ {
  hasStorageHostUrl_ = !!value_;
}
@synthesize storageHostUrl;
- (BOOL) hasDeviceSignUrl {
  return !!hasDeviceSignUrl_;
}
- (void) setHasDeviceSignUrl:(BOOL) value_ {
  hasDeviceSignUrl_ = !!value_;
}
@synthesize deviceSignUrl;
- (BOOL) hasPlainClientReportUrl {
  return !!hasPlainClientReportUrl_;
}
- (void) setHasPlainClientReportUrl:(BOOL) value_ {
  hasPlainClientReportUrl_ = !!value_;
}
@synthesize plainClientReportUrl;
- (BOOL) hasDownloadAllUrl {
  return !!hasDownloadAllUrl_;
}
- (void) setHasDownloadAllUrl:(BOOL) value_ {
  hasDownloadAllUrl_ = !!value_;
}
@synthesize downloadAllUrl;
- (BOOL) hasGetUserCloudSummaryUrl {
  return !!hasGetUserCloudSummaryUrl_;
}
- (void) setHasGetUserCloudSummaryUrl:(BOOL) value_ {
  hasGetUserCloudSummaryUrl_ = !!value_;
}
@synthesize getUserCloudSummaryUrl;
- (BOOL) hasQueryClientVersionUrl {
  return !!hasQueryClientVersionUrl_;
}
- (void) setHasQueryClientVersionUrl:(BOOL) value_ {
  hasQueryClientVersionUrl_ = !!value_;
}
@synthesize queryClientVersionUrl;
- (BOOL) hasQueryMobileNoUrl {
  return !!hasQueryMobileNoUrl_;
}
- (void) setHasQueryMobileNoUrl:(BOOL) value_ {
  hasQueryMobileNoUrl_ = !!value_;
}
@synthesize queryMobileNoUrl;
- (BOOL) hasGetSplashUrl {
  return !!hasGetSplashUrl_;
}
- (void) setHasGetSplashUrl:(BOOL) value_ {
  hasGetSplashUrl_ = !!value_;
}
@synthesize getSplashUrl;
- (BOOL) hasGetSysMsgUrl {
  return !!hasGetSysMsgUrl_;
}
- (void) setHasGetSysMsgUrl:(BOOL) value_ {
  hasGetSysMsgUrl_ = !!value_;
}
@synthesize getSysMsgUrl;
- (BOOL) hasQueryPublicInfoUrl {
  return !!hasQueryPublicInfoUrl_;
}
- (void) setHasQueryPublicInfoUrl:(BOOL) value_ {
  hasQueryPublicInfoUrl_ = !!value_;
}
@synthesize queryPublicInfoUrl;
- (BOOL) hasQueryCommentsUrl {
  return !!hasQueryCommentsUrl_;
}
- (void) setHasQueryCommentsUrl:(BOOL) value_ {
  hasQueryCommentsUrl_ = !!value_;
}
@synthesize queryCommentsUrl;
- (BOOL) hasUploadAllUrlV2 {
  return !!hasUploadAllUrlV2_;
}
- (void) setHasUploadAllUrlV2:(BOOL) value_ {
  hasUploadAllUrlV2_ = !!value_;
}
@synthesize uploadAllUrlV2;
- (void) dealloc {
  self.authUrl = nil;
  self.tpnoolUrl = nil;
  self.uploadPortraitUrl = nil;
  self.downloadPortraitUrl = nil;
  self.uploadAllUrl = nil;
  self.getContactListUrl = nil;
  self.downloadContactUrl = nil;
  self.syncUploadContactUrl = nil;
  self.getContactListVersionUrl = nil;
  self.slowSyncUrl = nil;
  self.syncPortraitUrl = nil;
  self.syncSmsUrl = nil;
  self.uploadSmsUrl = nil;
  self.downloadSmsUrl = nil;
  self.clientReportUrl = nil;
  self.backupCalllogUrl = nil;
  self.recoverCalllogUrl = nil;
  self.storageHostUrl = nil;
  self.deviceSignUrl = nil;
  self.plainClientReportUrl = nil;
  self.downloadAllUrl = nil;
  self.getUserCloudSummaryUrl = nil;
  self.queryClientVersionUrl = nil;
  self.queryMobileNoUrl = nil;
  self.getSplashUrl = nil;
  self.getSysMsgUrl = nil;
  self.queryPublicInfoUrl = nil;
  self.queryCommentsUrl = nil;
  self.uploadAllUrlV2 = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sessionExpires = 0;
    self.authUrl = @"";
    self.tpnoolVersion = 0;
    self.tpnoolUrl = @"";
    self.uploadPortraitUrl = @"";
    self.downloadPortraitUrl = @"";
    self.uploadAllUrl = @"";
    self.getContactListUrl = @"";
    self.downloadContactUrl = @"";
    self.syncUploadContactUrl = @"";
    self.getContactListVersionUrl = @"";
    self.slowSyncUrl = @"";
    self.syncPortraitUrl = @"";
    self.syncSmsUrl = @"";
    self.uploadSmsUrl = @"";
    self.downloadSmsUrl = @"";
    self.clientReportUrl = @"";
    self.backupCalllogUrl = @"";
    self.recoverCalllogUrl = @"";
    self.storageHostUrl = @"";
    self.deviceSignUrl = @"";
    self.plainClientReportUrl = @"";
    self.downloadAllUrl = @"";
    self.getUserCloudSummaryUrl = @"";
    self.queryClientVersionUrl = @"";
    self.queryMobileNoUrl = @"";
    self.getSplashUrl = @"";
    self.getSysMsgUrl = @"";
    self.queryPublicInfoUrl = @"";
    self.queryCommentsUrl = @"";
    self.uploadAllUrlV2 = @"";
  }
  return self;
}
static GetConfigResponse* defaultGetConfigResponseInstance = nil;
+ (void) initialize {
  if (self == [GetConfigResponse class]) {
    defaultGetConfigResponseInstance = [[GetConfigResponse alloc] init];
  }
}
+ (GetConfigResponse*) defaultInstance {
  return defaultGetConfigResponseInstance;
}
- (GetConfigResponse*) defaultInstance {
  return defaultGetConfigResponseInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output {
  if (self.hasSessionExpires) {
    [output writeUInt32:1 value:self.sessionExpires];
  }
  if (self.hasAuthUrl) {
    [output writeString:2 value:self.authUrl];
  }
  if (self.hasTpnoolVersion) {
    [output writeInt32:3 value:self.tpnoolVersion];
  }
  if (self.hasTpnoolUrl) {
    [output writeString:4 value:self.tpnoolUrl];
  }
  if (self.hasUploadPortraitUrl) {
    [output writeString:5 value:self.uploadPortraitUrl];
  }
  if (self.hasDownloadPortraitUrl) {
    [output writeString:6 value:self.downloadPortraitUrl];
  }
  if (self.hasUploadAllUrl) {
    [output writeString:7 value:self.uploadAllUrl];
  }
  if (self.hasGetContactListUrl) {
    [output writeString:8 value:self.getContactListUrl];
  }
  if (self.hasDownloadContactUrl) {
    [output writeString:9 value:self.downloadContactUrl];
  }
  if (self.hasSyncUploadContactUrl) {
    [output writeString:10 value:self.syncUploadContactUrl];
  }
  if (self.hasGetContactListVersionUrl) {
    [output writeString:11 value:self.getContactListVersionUrl];
  }
  if (self.hasSlowSyncUrl) {
    [output writeString:12 value:self.slowSyncUrl];
  }
  if (self.hasSyncPortraitUrl) {
    [output writeString:13 value:self.syncPortraitUrl];
  }
  if (self.hasSyncSmsUrl) {
    [output writeString:14 value:self.syncSmsUrl];
  }
  if (self.hasUploadSmsUrl) {
    [output writeString:15 value:self.uploadSmsUrl];
  }
  if (self.hasDownloadSmsUrl) {
    [output writeString:16 value:self.downloadSmsUrl];
  }
  if (self.hasClientReportUrl) {
    [output writeString:17 value:self.clientReportUrl];
  }
  if (self.hasBackupCalllogUrl) {
    [output writeString:18 value:self.backupCalllogUrl];
  }
  if (self.hasRecoverCalllogUrl) {
    [output writeString:19 value:self.recoverCalllogUrl];
  }
  if (self.hasStorageHostUrl) {
    [output writeString:20 value:self.storageHostUrl];
  }
  if (self.hasDeviceSignUrl) {
    [output writeString:21 value:self.deviceSignUrl];
  }
  if (self.hasPlainClientReportUrl) {
    [output writeString:22 value:self.plainClientReportUrl];
  }
  if (self.hasDownloadAllUrl) {
    [output writeString:23 value:self.downloadAllUrl];
  }
  if (self.hasGetUserCloudSummaryUrl) {
    [output writeString:24 value:self.getUserCloudSummaryUrl];
  }
  if (self.hasQueryClientVersionUrl) {
    [output writeString:25 value:self.queryClientVersionUrl];
  }
  if (self.hasQueryMobileNoUrl) {
    [output writeString:26 value:self.queryMobileNoUrl];
  }
  if (self.hasGetSplashUrl) {
    [output writeString:27 value:self.getSplashUrl];
  }
  if (self.hasGetSysMsgUrl) {
    [output writeString:28 value:self.getSysMsgUrl];
  }
  if (self.hasQueryPublicInfoUrl) {
    [output writeString:29 value:self.queryPublicInfoUrl];
  }
  if (self.hasQueryCommentsUrl) {
    [output writeString:30 value:self.queryCommentsUrl];
  }
  if (self.hasUploadAllUrlV2) {
    [output writeString:31 value:self.uploadAllUrlV2];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSessionExpires) {
    size_ += ES_computeUInt32Size(1, self.sessionExpires);
  }
  if (self.hasAuthUrl) {
    size_ += ES_computeStringSize(2, self.authUrl);
  }
  if (self.hasTpnoolVersion) {
    size_ += ES_computeInt32Size(3, self.tpnoolVersion);
  }
  if (self.hasTpnoolUrl) {
    size_ += ES_computeStringSize(4, self.tpnoolUrl);
  }
  if (self.hasUploadPortraitUrl) {
    size_ += ES_computeStringSize(5, self.uploadPortraitUrl);
  }
  if (self.hasDownloadPortraitUrl) {
    size_ += ES_computeStringSize(6, self.downloadPortraitUrl);
  }
  if (self.hasUploadAllUrl) {
    size_ += ES_computeStringSize(7, self.uploadAllUrl);
  }
  if (self.hasGetContactListUrl) {
    size_ += ES_computeStringSize(8, self.getContactListUrl);
  }
  if (self.hasDownloadContactUrl) {
    size_ += ES_computeStringSize(9, self.downloadContactUrl);
  }
  if (self.hasSyncUploadContactUrl) {
    size_ += ES_computeStringSize(10, self.syncUploadContactUrl);
  }
  if (self.hasGetContactListVersionUrl) {
    size_ += ES_computeStringSize(11, self.getContactListVersionUrl);
  }
  if (self.hasSlowSyncUrl) {
    size_ += ES_computeStringSize(12, self.slowSyncUrl);
  }
  if (self.hasSyncPortraitUrl) {
    size_ += ES_computeStringSize(13, self.syncPortraitUrl);
  }
  if (self.hasSyncSmsUrl) {
    size_ += ES_computeStringSize(14, self.syncSmsUrl);
  }
  if (self.hasUploadSmsUrl) {
    size_ += ES_computeStringSize(15, self.uploadSmsUrl);
  }
  if (self.hasDownloadSmsUrl) {
    size_ += ES_computeStringSize(16, self.downloadSmsUrl);
  }
  if (self.hasClientReportUrl) {
    size_ += ES_computeStringSize(17, self.clientReportUrl);
  }
  if (self.hasBackupCalllogUrl) {
    size_ += ES_computeStringSize(18, self.backupCalllogUrl);
  }
  if (self.hasRecoverCalllogUrl) {
    size_ += ES_computeStringSize(19, self.recoverCalllogUrl);
  }
  if (self.hasStorageHostUrl) {
    size_ += ES_computeStringSize(20, self.storageHostUrl);
  }
  if (self.hasDeviceSignUrl) {
    size_ += ES_computeStringSize(21, self.deviceSignUrl);
  }
  if (self.hasPlainClientReportUrl) {
    size_ += ES_computeStringSize(22, self.plainClientReportUrl);
  }
  if (self.hasDownloadAllUrl) {
    size_ += ES_computeStringSize(23, self.downloadAllUrl);
  }
  if (self.hasGetUserCloudSummaryUrl) {
    size_ += ES_computeStringSize(24, self.getUserCloudSummaryUrl);
  }
  if (self.hasQueryClientVersionUrl) {
    size_ += ES_computeStringSize(25, self.queryClientVersionUrl);
  }
  if (self.hasQueryMobileNoUrl) {
    size_ += ES_computeStringSize(26, self.queryMobileNoUrl);
  }
  if (self.hasGetSplashUrl) {
    size_ += ES_computeStringSize(27, self.getSplashUrl);
  }
  if (self.hasGetSysMsgUrl) {
    size_ += ES_computeStringSize(28, self.getSysMsgUrl);
  }
  if (self.hasQueryPublicInfoUrl) {
    size_ += ES_computeStringSize(29, self.queryPublicInfoUrl);
  }
  if (self.hasQueryCommentsUrl) {
    size_ += ES_computeStringSize(30, self.queryCommentsUrl);
  }
  if (self.hasUploadAllUrlV2) {
    size_ += ES_computeStringSize(31, self.uploadAllUrlV2);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetConfigResponse*) parseFromData:(NSData*) data {
  return (GetConfigResponse*)[[[GetConfigResponse builder] mergeFromData:data] build];
}
+ (GetConfigResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (GetConfigResponse*)[[[GetConfigResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (GetConfigResponse*) parseFromInputStream:(NSInputStream*) input {
  return (GetConfigResponse*)[[[GetConfigResponse builder] mergeFromInputStream:input] build];
}
+ (GetConfigResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (GetConfigResponse*)[[[GetConfigResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetConfigResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return (GetConfigResponse*)[[[GetConfigResponse builder] mergeFromCodedInputStream:input] build];
}
+ (GetConfigResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (GetConfigResponse*)[[[GetConfigResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetConfigResponse_Builder*) builder {
  return [[[GetConfigResponse_Builder alloc] init] autorelease];
}
+ (GetConfigResponse_Builder*) builderWithPrototype:(GetConfigResponse*) prototype {
  return [[GetConfigResponse builder] mergeFrom:prototype];
}
- (GetConfigResponse_Builder*) builder {
  return [GetConfigResponse builder];
}
- (GetConfigResponse_Builder*) toBuilder {
  return [GetConfigResponse builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSessionExpires) {
    [output appendFormat:@"%@%@: %@\n", indent, @"sessionExpires", [NSNumber numberWithInt:self.sessionExpires]];
  }
  if (self.hasAuthUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"authUrl", self.authUrl];
  }
  if (self.hasTpnoolVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"tpnoolVersion", [NSNumber numberWithInt:self.tpnoolVersion]];
  }
  if (self.hasTpnoolUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"tpnoolUrl", self.tpnoolUrl];
  }
  if (self.hasUploadPortraitUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uploadPortraitUrl", self.uploadPortraitUrl];
  }
  if (self.hasDownloadPortraitUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"downloadPortraitUrl", self.downloadPortraitUrl];
  }
  if (self.hasUploadAllUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uploadAllUrl", self.uploadAllUrl];
  }
  if (self.hasGetContactListUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"getContactListUrl", self.getContactListUrl];
  }
  if (self.hasDownloadContactUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"downloadContactUrl", self.downloadContactUrl];
  }
  if (self.hasSyncUploadContactUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"syncUploadContactUrl", self.syncUploadContactUrl];
  }
  if (self.hasGetContactListVersionUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"getContactListVersionUrl", self.getContactListVersionUrl];
  }
  if (self.hasSlowSyncUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"slowSyncUrl", self.slowSyncUrl];
  }
  if (self.hasSyncPortraitUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"syncPortraitUrl", self.syncPortraitUrl];
  }
  if (self.hasSyncSmsUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"syncSmsUrl", self.syncSmsUrl];
  }
  if (self.hasUploadSmsUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uploadSmsUrl", self.uploadSmsUrl];
  }
  if (self.hasDownloadSmsUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"downloadSmsUrl", self.downloadSmsUrl];
  }
  if (self.hasClientReportUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"clientReportUrl", self.clientReportUrl];
  }
  if (self.hasBackupCalllogUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"backupCalllogUrl", self.backupCalllogUrl];
  }
  if (self.hasRecoverCalllogUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"recoverCalllogUrl", self.recoverCalllogUrl];
  }
  if (self.hasStorageHostUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"storageHostUrl", self.storageHostUrl];
  }
  if (self.hasDeviceSignUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"deviceSignUrl", self.deviceSignUrl];
  }
  if (self.hasPlainClientReportUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"plainClientReportUrl", self.plainClientReportUrl];
  }
  if (self.hasDownloadAllUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"downloadAllUrl", self.downloadAllUrl];
  }
  if (self.hasGetUserCloudSummaryUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"getUserCloudSummaryUrl", self.getUserCloudSummaryUrl];
  }
  if (self.hasQueryClientVersionUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"queryClientVersionUrl", self.queryClientVersionUrl];
  }
  if (self.hasQueryMobileNoUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"queryMobileNoUrl", self.queryMobileNoUrl];
  }
  if (self.hasGetSplashUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"getSplashUrl", self.getSplashUrl];
  }
  if (self.hasGetSysMsgUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"getSysMsgUrl", self.getSysMsgUrl];
  }
  if (self.hasQueryPublicInfoUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"queryPublicInfoUrl", self.queryPublicInfoUrl];
  }
  if (self.hasQueryCommentsUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"queryCommentsUrl", self.queryCommentsUrl];
  }
  if (self.hasUploadAllUrlV2) {
    [output appendFormat:@"%@%@: %@\n", indent, @"uploadAllUrlV2", self.uploadAllUrlV2];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[GetConfigResponse class]]) {
    return NO;
  }
  GetConfigResponse *otherMessage = other;
  return
      self.hasSessionExpires == otherMessage.hasSessionExpires &&
      (!self.hasSessionExpires || self.sessionExpires == otherMessage.sessionExpires) &&
      self.hasAuthUrl == otherMessage.hasAuthUrl &&
      (!self.hasAuthUrl || [self.authUrl isEqual:otherMessage.authUrl]) &&
      self.hasTpnoolVersion == otherMessage.hasTpnoolVersion &&
      (!self.hasTpnoolVersion || self.tpnoolVersion == otherMessage.tpnoolVersion) &&
      self.hasTpnoolUrl == otherMessage.hasTpnoolUrl &&
      (!self.hasTpnoolUrl || [self.tpnoolUrl isEqual:otherMessage.tpnoolUrl]) &&
      self.hasUploadPortraitUrl == otherMessage.hasUploadPortraitUrl &&
      (!self.hasUploadPortraitUrl || [self.uploadPortraitUrl isEqual:otherMessage.uploadPortraitUrl]) &&
      self.hasDownloadPortraitUrl == otherMessage.hasDownloadPortraitUrl &&
      (!self.hasDownloadPortraitUrl || [self.downloadPortraitUrl isEqual:otherMessage.downloadPortraitUrl]) &&
      self.hasUploadAllUrl == otherMessage.hasUploadAllUrl &&
      (!self.hasUploadAllUrl || [self.uploadAllUrl isEqual:otherMessage.uploadAllUrl]) &&
      self.hasGetContactListUrl == otherMessage.hasGetContactListUrl &&
      (!self.hasGetContactListUrl || [self.getContactListUrl isEqual:otherMessage.getContactListUrl]) &&
      self.hasDownloadContactUrl == otherMessage.hasDownloadContactUrl &&
      (!self.hasDownloadContactUrl || [self.downloadContactUrl isEqual:otherMessage.downloadContactUrl]) &&
      self.hasSyncUploadContactUrl == otherMessage.hasSyncUploadContactUrl &&
      (!self.hasSyncUploadContactUrl || [self.syncUploadContactUrl isEqual:otherMessage.syncUploadContactUrl]) &&
      self.hasGetContactListVersionUrl == otherMessage.hasGetContactListVersionUrl &&
      (!self.hasGetContactListVersionUrl || [self.getContactListVersionUrl isEqual:otherMessage.getContactListVersionUrl]) &&
      self.hasSlowSyncUrl == otherMessage.hasSlowSyncUrl &&
      (!self.hasSlowSyncUrl || [self.slowSyncUrl isEqual:otherMessage.slowSyncUrl]) &&
      self.hasSyncPortraitUrl == otherMessage.hasSyncPortraitUrl &&
      (!self.hasSyncPortraitUrl || [self.syncPortraitUrl isEqual:otherMessage.syncPortraitUrl]) &&
      self.hasSyncSmsUrl == otherMessage.hasSyncSmsUrl &&
      (!self.hasSyncSmsUrl || [self.syncSmsUrl isEqual:otherMessage.syncSmsUrl]) &&
      self.hasUploadSmsUrl == otherMessage.hasUploadSmsUrl &&
      (!self.hasUploadSmsUrl || [self.uploadSmsUrl isEqual:otherMessage.uploadSmsUrl]) &&
      self.hasDownloadSmsUrl == otherMessage.hasDownloadSmsUrl &&
      (!self.hasDownloadSmsUrl || [self.downloadSmsUrl isEqual:otherMessage.downloadSmsUrl]) &&
      self.hasClientReportUrl == otherMessage.hasClientReportUrl &&
      (!self.hasClientReportUrl || [self.clientReportUrl isEqual:otherMessage.clientReportUrl]) &&
      self.hasBackupCalllogUrl == otherMessage.hasBackupCalllogUrl &&
      (!self.hasBackupCalllogUrl || [self.backupCalllogUrl isEqual:otherMessage.backupCalllogUrl]) &&
      self.hasRecoverCalllogUrl == otherMessage.hasRecoverCalllogUrl &&
      (!self.hasRecoverCalllogUrl || [self.recoverCalllogUrl isEqual:otherMessage.recoverCalllogUrl]) &&
      self.hasStorageHostUrl == otherMessage.hasStorageHostUrl &&
      (!self.hasStorageHostUrl || [self.storageHostUrl isEqual:otherMessage.storageHostUrl]) &&
      self.hasDeviceSignUrl == otherMessage.hasDeviceSignUrl &&
      (!self.hasDeviceSignUrl || [self.deviceSignUrl isEqual:otherMessage.deviceSignUrl]) &&
      self.hasPlainClientReportUrl == otherMessage.hasPlainClientReportUrl &&
      (!self.hasPlainClientReportUrl || [self.plainClientReportUrl isEqual:otherMessage.plainClientReportUrl]) &&
      self.hasDownloadAllUrl == otherMessage.hasDownloadAllUrl &&
      (!self.hasDownloadAllUrl || [self.downloadAllUrl isEqual:otherMessage.downloadAllUrl]) &&
      self.hasGetUserCloudSummaryUrl == otherMessage.hasGetUserCloudSummaryUrl &&
      (!self.hasGetUserCloudSummaryUrl || [self.getUserCloudSummaryUrl isEqual:otherMessage.getUserCloudSummaryUrl]) &&
      self.hasQueryClientVersionUrl == otherMessage.hasQueryClientVersionUrl &&
      (!self.hasQueryClientVersionUrl || [self.queryClientVersionUrl isEqual:otherMessage.queryClientVersionUrl]) &&
      self.hasQueryMobileNoUrl == otherMessage.hasQueryMobileNoUrl &&
      (!self.hasQueryMobileNoUrl || [self.queryMobileNoUrl isEqual:otherMessage.queryMobileNoUrl]) &&
      self.hasGetSplashUrl == otherMessage.hasGetSplashUrl &&
      (!self.hasGetSplashUrl || [self.getSplashUrl isEqual:otherMessage.getSplashUrl]) &&
      self.hasGetSysMsgUrl == otherMessage.hasGetSysMsgUrl &&
      (!self.hasGetSysMsgUrl || [self.getSysMsgUrl isEqual:otherMessage.getSysMsgUrl]) &&
      self.hasQueryPublicInfoUrl == otherMessage.hasQueryPublicInfoUrl &&
      (!self.hasQueryPublicInfoUrl || [self.queryPublicInfoUrl isEqual:otherMessage.queryPublicInfoUrl]) &&
      self.hasQueryCommentsUrl == otherMessage.hasQueryCommentsUrl &&
      (!self.hasQueryCommentsUrl || [self.queryCommentsUrl isEqual:otherMessage.queryCommentsUrl]) &&
      self.hasUploadAllUrlV2 == otherMessage.hasUploadAllUrlV2 &&
      (!self.hasUploadAllUrlV2 || [self.uploadAllUrlV2 isEqual:otherMessage.uploadAllUrlV2]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasSessionExpires) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.sessionExpires] hash];
  }
  if (self.hasAuthUrl) {
    hashCode = hashCode * 31 + [self.authUrl hash];
  }
  if (self.hasTpnoolVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.tpnoolVersion] hash];
  }
  if (self.hasTpnoolUrl) {
    hashCode = hashCode * 31 + [self.tpnoolUrl hash];
  }
  if (self.hasUploadPortraitUrl) {
    hashCode = hashCode * 31 + [self.uploadPortraitUrl hash];
  }
  if (self.hasDownloadPortraitUrl) {
    hashCode = hashCode * 31 + [self.downloadPortraitUrl hash];
  }
  if (self.hasUploadAllUrl) {
    hashCode = hashCode * 31 + [self.uploadAllUrl hash];
  }
  if (self.hasGetContactListUrl) {
    hashCode = hashCode * 31 + [self.getContactListUrl hash];
  }
  if (self.hasDownloadContactUrl) {
    hashCode = hashCode * 31 + [self.downloadContactUrl hash];
  }
  if (self.hasSyncUploadContactUrl) {
    hashCode = hashCode * 31 + [self.syncUploadContactUrl hash];
  }
  if (self.hasGetContactListVersionUrl) {
    hashCode = hashCode * 31 + [self.getContactListVersionUrl hash];
  }
  if (self.hasSlowSyncUrl) {
    hashCode = hashCode * 31 + [self.slowSyncUrl hash];
  }
  if (self.hasSyncPortraitUrl) {
    hashCode = hashCode * 31 + [self.syncPortraitUrl hash];
  }
  if (self.hasSyncSmsUrl) {
    hashCode = hashCode * 31 + [self.syncSmsUrl hash];
  }
  if (self.hasUploadSmsUrl) {
    hashCode = hashCode * 31 + [self.uploadSmsUrl hash];
  }
  if (self.hasDownloadSmsUrl) {
    hashCode = hashCode * 31 + [self.downloadSmsUrl hash];
  }
  if (self.hasClientReportUrl) {
    hashCode = hashCode * 31 + [self.clientReportUrl hash];
  }
  if (self.hasBackupCalllogUrl) {
    hashCode = hashCode * 31 + [self.backupCalllogUrl hash];
  }
  if (self.hasRecoverCalllogUrl) {
    hashCode = hashCode * 31 + [self.recoverCalllogUrl hash];
  }
  if (self.hasStorageHostUrl) {
    hashCode = hashCode * 31 + [self.storageHostUrl hash];
  }
  if (self.hasDeviceSignUrl) {
    hashCode = hashCode * 31 + [self.deviceSignUrl hash];
  }
  if (self.hasPlainClientReportUrl) {
    hashCode = hashCode * 31 + [self.plainClientReportUrl hash];
  }
  if (self.hasDownloadAllUrl) {
    hashCode = hashCode * 31 + [self.downloadAllUrl hash];
  }
  if (self.hasGetUserCloudSummaryUrl) {
    hashCode = hashCode * 31 + [self.getUserCloudSummaryUrl hash];
  }
  if (self.hasQueryClientVersionUrl) {
    hashCode = hashCode * 31 + [self.queryClientVersionUrl hash];
  }
  if (self.hasQueryMobileNoUrl) {
    hashCode = hashCode * 31 + [self.queryMobileNoUrl hash];
  }
  if (self.hasGetSplashUrl) {
    hashCode = hashCode * 31 + [self.getSplashUrl hash];
  }
  if (self.hasGetSysMsgUrl) {
    hashCode = hashCode * 31 + [self.getSysMsgUrl hash];
  }
  if (self.hasQueryPublicInfoUrl) {
    hashCode = hashCode * 31 + [self.queryPublicInfoUrl hash];
  }
  if (self.hasQueryCommentsUrl) {
    hashCode = hashCode * 31 + [self.queryCommentsUrl hash];
  }
  if (self.hasUploadAllUrlV2) {
    hashCode = hashCode * 31 + [self.uploadAllUrlV2 hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface GetConfigResponse_Builder()
@property (retain) GetConfigResponse* result;
@end

@implementation GetConfigResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[GetConfigResponse alloc] init] autorelease];
  }
  return self;
}
- (ES_PBGeneratedMessage*) internalGetResult {
  return result;
}
- (GetConfigResponse_Builder*) clear {
  self.result = [[[GetConfigResponse alloc] init] autorelease];
  return self;
}
- (GetConfigResponse_Builder*) clone {
  return [GetConfigResponse builderWithPrototype:result];
}
- (GetConfigResponse*) defaultInstance {
  return [GetConfigResponse defaultInstance];
}
- (GetConfigResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (GetConfigResponse*) buildPartial {
  GetConfigResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (GetConfigResponse_Builder*) mergeFrom:(GetConfigResponse*) other {
  if (other == [GetConfigResponse defaultInstance]) {
    return self;
  }
  if (other.hasSessionExpires) {
    [self setSessionExpires:other.sessionExpires];
  }
  if (other.hasAuthUrl) {
    [self setAuthUrl:other.authUrl];
  }
  if (other.hasTpnoolVersion) {
    [self setTpnoolVersion:other.tpnoolVersion];
  }
  if (other.hasTpnoolUrl) {
    [self setTpnoolUrl:other.tpnoolUrl];
  }
  if (other.hasUploadPortraitUrl) {
    [self setUploadPortraitUrl:other.uploadPortraitUrl];
  }
  if (other.hasDownloadPortraitUrl) {
    [self setDownloadPortraitUrl:other.downloadPortraitUrl];
  }
  if (other.hasUploadAllUrl) {
    [self setUploadAllUrl:other.uploadAllUrl];
  }
  if (other.hasGetContactListUrl) {
    [self setGetContactListUrl:other.getContactListUrl];
  }
  if (other.hasDownloadContactUrl) {
    [self setDownloadContactUrl:other.downloadContactUrl];
  }
  if (other.hasSyncUploadContactUrl) {
    [self setSyncUploadContactUrl:other.syncUploadContactUrl];
  }
  if (other.hasGetContactListVersionUrl) {
    [self setGetContactListVersionUrl:other.getContactListVersionUrl];
  }
  if (other.hasSlowSyncUrl) {
    [self setSlowSyncUrl:other.slowSyncUrl];
  }
  if (other.hasSyncPortraitUrl) {
    [self setSyncPortraitUrl:other.syncPortraitUrl];
  }
  if (other.hasSyncSmsUrl) {
    [self setSyncSmsUrl:other.syncSmsUrl];
  }
  if (other.hasUploadSmsUrl) {
    [self setUploadSmsUrl:other.uploadSmsUrl];
  }
  if (other.hasDownloadSmsUrl) {
    [self setDownloadSmsUrl:other.downloadSmsUrl];
  }
  if (other.hasClientReportUrl) {
    [self setClientReportUrl:other.clientReportUrl];
  }
  if (other.hasBackupCalllogUrl) {
    [self setBackupCalllogUrl:other.backupCalllogUrl];
  }
  if (other.hasRecoverCalllogUrl) {
    [self setRecoverCalllogUrl:other.recoverCalllogUrl];
  }
  if (other.hasStorageHostUrl) {
    [self setStorageHostUrl:other.storageHostUrl];
  }
  if (other.hasDeviceSignUrl) {
    [self setDeviceSignUrl:other.deviceSignUrl];
  }
  if (other.hasPlainClientReportUrl) {
    [self setPlainClientReportUrl:other.plainClientReportUrl];
  }
  if (other.hasDownloadAllUrl) {
    [self setDownloadAllUrl:other.downloadAllUrl];
  }
  if (other.hasGetUserCloudSummaryUrl) {
    [self setGetUserCloudSummaryUrl:other.getUserCloudSummaryUrl];
  }
  if (other.hasQueryClientVersionUrl) {
    [self setQueryClientVersionUrl:other.queryClientVersionUrl];
  }
  if (other.hasQueryMobileNoUrl) {
    [self setQueryMobileNoUrl:other.queryMobileNoUrl];
  }
  if (other.hasGetSplashUrl) {
    [self setGetSplashUrl:other.getSplashUrl];
  }
  if (other.hasGetSysMsgUrl) {
    [self setGetSysMsgUrl:other.getSysMsgUrl];
  }
  if (other.hasQueryPublicInfoUrl) {
    [self setQueryPublicInfoUrl:other.queryPublicInfoUrl];
  }
  if (other.hasQueryCommentsUrl) {
    [self setQueryCommentsUrl:other.queryCommentsUrl];
  }
  if (other.hasUploadAllUrlV2) {
    [self setUploadAllUrlV2:other.uploadAllUrlV2];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (GetConfigResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[ES_PBExtensionRegistry emptyRegistry]];
}
- (GetConfigResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  ES_PBUnknownFieldSet_Builder* unknownFields = [ES_PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setSessionExpires:[input readUInt32]];
        break;
      }
      case 18: {
        [self setAuthUrl:[input readString]];
        break;
      }
      case 24: {
        [self setTpnoolVersion:[input readInt32]];
        break;
      }
      case 34: {
        [self setTpnoolUrl:[input readString]];
        break;
      }
      case 42: {
        [self setUploadPortraitUrl:[input readString]];
        break;
      }
      case 50: {
        [self setDownloadPortraitUrl:[input readString]];
        break;
      }
      case 58: {
        [self setUploadAllUrl:[input readString]];
        break;
      }
      case 66: {
        [self setGetContactListUrl:[input readString]];
        break;
      }
      case 74: {
        [self setDownloadContactUrl:[input readString]];
        break;
      }
      case 82: {
        [self setSyncUploadContactUrl:[input readString]];
        break;
      }
      case 90: {
        [self setGetContactListVersionUrl:[input readString]];
        break;
      }
      case 98: {
        [self setSlowSyncUrl:[input readString]];
        break;
      }
      case 106: {
        [self setSyncPortraitUrl:[input readString]];
        break;
      }
      case 114: {
        [self setSyncSmsUrl:[input readString]];
        break;
      }
      case 122: {
        [self setUploadSmsUrl:[input readString]];
        break;
      }
      case 130: {
        [self setDownloadSmsUrl:[input readString]];
        break;
      }
      case 138: {
        [self setClientReportUrl:[input readString]];
        break;
      }
      case 146: {
        [self setBackupCalllogUrl:[input readString]];
        break;
      }
      case 154: {
        [self setRecoverCalllogUrl:[input readString]];
        break;
      }
      case 162: {
        [self setStorageHostUrl:[input readString]];
        break;
      }
      case 170: {
        [self setDeviceSignUrl:[input readString]];
        break;
      }
      case 178: {
        [self setPlainClientReportUrl:[input readString]];
        break;
      }
      case 186: {
        [self setDownloadAllUrl:[input readString]];
        break;
      }
      case 194: {
        [self setGetUserCloudSummaryUrl:[input readString]];
        break;
      }
      case 202: {
        [self setQueryClientVersionUrl:[input readString]];
        break;
      }
      case 210: {
        [self setQueryMobileNoUrl:[input readString]];
        break;
      }
      case 218: {
        [self setGetSplashUrl:[input readString]];
        break;
      }
      case 226: {
        [self setGetSysMsgUrl:[input readString]];
        break;
      }
      case 234: {
        [self setQueryPublicInfoUrl:[input readString]];
        break;
      }
      case 242: {
        [self setQueryCommentsUrl:[input readString]];
        break;
      }
      case 250: {
        [self setUploadAllUrlV2:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasSessionExpires {
  return result.hasSessionExpires;
}
- (uint32_t) sessionExpires {
  return result.sessionExpires;
}
- (GetConfigResponse_Builder*) setSessionExpires:(uint32_t) value {
  result.hasSessionExpires = YES;
  result.sessionExpires = value;
  return self;
}
- (GetConfigResponse_Builder*) clearSessionExpires {
  result.hasSessionExpires = NO;
  result.sessionExpires = 0;
  return self;
}
- (BOOL) hasAuthUrl {
  return result.hasAuthUrl;
}
- (NSString*) authUrl {
  return result.authUrl;
}
- (GetConfigResponse_Builder*) setAuthUrl:(NSString*) value {
  result.hasAuthUrl = YES;
  result.authUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearAuthUrl {
  result.hasAuthUrl = NO;
  result.authUrl = @"";
  return self;
}
- (BOOL) hasTpnoolVersion {
  return result.hasTpnoolVersion;
}
- (int32_t) tpnoolVersion {
  return result.tpnoolVersion;
}
- (GetConfigResponse_Builder*) setTpnoolVersion:(int32_t) value {
  result.hasTpnoolVersion = YES;
  result.tpnoolVersion = value;
  return self;
}
- (GetConfigResponse_Builder*) clearTpnoolVersion {
  result.hasTpnoolVersion = NO;
  result.tpnoolVersion = 0;
  return self;
}
- (BOOL) hasTpnoolUrl {
  return result.hasTpnoolUrl;
}
- (NSString*) tpnoolUrl {
  return result.tpnoolUrl;
}
- (GetConfigResponse_Builder*) setTpnoolUrl:(NSString*) value {
  result.hasTpnoolUrl = YES;
  result.tpnoolUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearTpnoolUrl {
  result.hasTpnoolUrl = NO;
  result.tpnoolUrl = @"";
  return self;
}
- (BOOL) hasUploadPortraitUrl {
  return result.hasUploadPortraitUrl;
}
- (NSString*) uploadPortraitUrl {
  return result.uploadPortraitUrl;
}
- (GetConfigResponse_Builder*) setUploadPortraitUrl:(NSString*) value {
  result.hasUploadPortraitUrl = YES;
  result.uploadPortraitUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearUploadPortraitUrl {
  result.hasUploadPortraitUrl = NO;
  result.uploadPortraitUrl = @"";
  return self;
}
- (BOOL) hasDownloadPortraitUrl {
  return result.hasDownloadPortraitUrl;
}
- (NSString*) downloadPortraitUrl {
  return result.downloadPortraitUrl;
}
- (GetConfigResponse_Builder*) setDownloadPortraitUrl:(NSString*) value {
  result.hasDownloadPortraitUrl = YES;
  result.downloadPortraitUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearDownloadPortraitUrl {
  result.hasDownloadPortraitUrl = NO;
  result.downloadPortraitUrl = @"";
  return self;
}
- (BOOL) hasUploadAllUrl {
  return result.hasUploadAllUrl;
}
- (NSString*) uploadAllUrl {
  return result.uploadAllUrl;
}
- (GetConfigResponse_Builder*) setUploadAllUrl:(NSString*) value {
  result.hasUploadAllUrl = YES;
  result.uploadAllUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearUploadAllUrl {
  result.hasUploadAllUrl = NO;
  result.uploadAllUrl = @"";
  return self;
}
- (BOOL) hasGetContactListUrl {
  return result.hasGetContactListUrl;
}
- (NSString*) getContactListUrl {
  return result.getContactListUrl;
}
- (GetConfigResponse_Builder*) setGetContactListUrl:(NSString*) value {
  result.hasGetContactListUrl = YES;
  result.getContactListUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearGetContactListUrl {
  result.hasGetContactListUrl = NO;
  result.getContactListUrl = @"";
  return self;
}
- (BOOL) hasDownloadContactUrl {
  return result.hasDownloadContactUrl;
}
- (NSString*) downloadContactUrl {
  return result.downloadContactUrl;
}
- (GetConfigResponse_Builder*) setDownloadContactUrl:(NSString*) value {
  result.hasDownloadContactUrl = YES;
  result.downloadContactUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearDownloadContactUrl {
  result.hasDownloadContactUrl = NO;
  result.downloadContactUrl = @"";
  return self;
}
- (BOOL) hasSyncUploadContactUrl {
  return result.hasSyncUploadContactUrl;
}
- (NSString*) syncUploadContactUrl {
  return result.syncUploadContactUrl;
}
- (GetConfigResponse_Builder*) setSyncUploadContactUrl:(NSString*) value {
  result.hasSyncUploadContactUrl = YES;
  result.syncUploadContactUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearSyncUploadContactUrl {
  result.hasSyncUploadContactUrl = NO;
  result.syncUploadContactUrl = @"";
  return self;
}
- (BOOL) hasGetContactListVersionUrl {
  return result.hasGetContactListVersionUrl;
}
- (NSString*) getContactListVersionUrl {
  return result.getContactListVersionUrl;
}
- (GetConfigResponse_Builder*) setGetContactListVersionUrl:(NSString*) value {
  result.hasGetContactListVersionUrl = YES;
  result.getContactListVersionUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearGetContactListVersionUrl {
  result.hasGetContactListVersionUrl = NO;
  result.getContactListVersionUrl = @"";
  return self;
}
- (BOOL) hasSlowSyncUrl {
  return result.hasSlowSyncUrl;
}
- (NSString*) slowSyncUrl {
  return result.slowSyncUrl;
}
- (GetConfigResponse_Builder*) setSlowSyncUrl:(NSString*) value {
  result.hasSlowSyncUrl = YES;
  result.slowSyncUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearSlowSyncUrl {
  result.hasSlowSyncUrl = NO;
  result.slowSyncUrl = @"";
  return self;
}
- (BOOL) hasSyncPortraitUrl {
  return result.hasSyncPortraitUrl;
}
- (NSString*) syncPortraitUrl {
  return result.syncPortraitUrl;
}
- (GetConfigResponse_Builder*) setSyncPortraitUrl:(NSString*) value {
  result.hasSyncPortraitUrl = YES;
  result.syncPortraitUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearSyncPortraitUrl {
  result.hasSyncPortraitUrl = NO;
  result.syncPortraitUrl = @"";
  return self;
}
- (BOOL) hasSyncSmsUrl {
  return result.hasSyncSmsUrl;
}
- (NSString*) syncSmsUrl {
  return result.syncSmsUrl;
}
- (GetConfigResponse_Builder*) setSyncSmsUrl:(NSString*) value {
  result.hasSyncSmsUrl = YES;
  result.syncSmsUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearSyncSmsUrl {
  result.hasSyncSmsUrl = NO;
  result.syncSmsUrl = @"";
  return self;
}
- (BOOL) hasUploadSmsUrl {
  return result.hasUploadSmsUrl;
}
- (NSString*) uploadSmsUrl {
  return result.uploadSmsUrl;
}
- (GetConfigResponse_Builder*) setUploadSmsUrl:(NSString*) value {
  result.hasUploadSmsUrl = YES;
  result.uploadSmsUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearUploadSmsUrl {
  result.hasUploadSmsUrl = NO;
  result.uploadSmsUrl = @"";
  return self;
}
- (BOOL) hasDownloadSmsUrl {
  return result.hasDownloadSmsUrl;
}
- (NSString*) downloadSmsUrl {
  return result.downloadSmsUrl;
}
- (GetConfigResponse_Builder*) setDownloadSmsUrl:(NSString*) value {
  result.hasDownloadSmsUrl = YES;
  result.downloadSmsUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearDownloadSmsUrl {
  result.hasDownloadSmsUrl = NO;
  result.downloadSmsUrl = @"";
  return self;
}
- (BOOL) hasClientReportUrl {
  return result.hasClientReportUrl;
}
- (NSString*) clientReportUrl {
  return result.clientReportUrl;
}
- (GetConfigResponse_Builder*) setClientReportUrl:(NSString*) value {
  result.hasClientReportUrl = YES;
  result.clientReportUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearClientReportUrl {
  result.hasClientReportUrl = NO;
  result.clientReportUrl = @"";
  return self;
}
- (BOOL) hasBackupCalllogUrl {
  return result.hasBackupCalllogUrl;
}
- (NSString*) backupCalllogUrl {
  return result.backupCalllogUrl;
}
- (GetConfigResponse_Builder*) setBackupCalllogUrl:(NSString*) value {
  result.hasBackupCalllogUrl = YES;
  result.backupCalllogUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearBackupCalllogUrl {
  result.hasBackupCalllogUrl = NO;
  result.backupCalllogUrl = @"";
  return self;
}
- (BOOL) hasRecoverCalllogUrl {
  return result.hasRecoverCalllogUrl;
}
- (NSString*) recoverCalllogUrl {
  return result.recoverCalllogUrl;
}
- (GetConfigResponse_Builder*) setRecoverCalllogUrl:(NSString*) value {
  result.hasRecoverCalllogUrl = YES;
  result.recoverCalllogUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearRecoverCalllogUrl {
  result.hasRecoverCalllogUrl = NO;
  result.recoverCalllogUrl = @"";
  return self;
}
- (BOOL) hasStorageHostUrl {
  return result.hasStorageHostUrl;
}
- (NSString*) storageHostUrl {
  return result.storageHostUrl;
}
- (GetConfigResponse_Builder*) setStorageHostUrl:(NSString*) value {
  result.hasStorageHostUrl = YES;
  result.storageHostUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearStorageHostUrl {
  result.hasStorageHostUrl = NO;
  result.storageHostUrl = @"";
  return self;
}
- (BOOL) hasDeviceSignUrl {
  return result.hasDeviceSignUrl;
}
- (NSString*) deviceSignUrl {
  return result.deviceSignUrl;
}
- (GetConfigResponse_Builder*) setDeviceSignUrl:(NSString*) value {
  result.hasDeviceSignUrl = YES;
  result.deviceSignUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearDeviceSignUrl {
  result.hasDeviceSignUrl = NO;
  result.deviceSignUrl = @"";
  return self;
}
- (BOOL) hasPlainClientReportUrl {
  return result.hasPlainClientReportUrl;
}
- (NSString*) plainClientReportUrl {
  return result.plainClientReportUrl;
}
- (GetConfigResponse_Builder*) setPlainClientReportUrl:(NSString*) value {
  result.hasPlainClientReportUrl = YES;
  result.plainClientReportUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearPlainClientReportUrl {
  result.hasPlainClientReportUrl = NO;
  result.plainClientReportUrl = @"";
  return self;
}
- (BOOL) hasDownloadAllUrl {
  return result.hasDownloadAllUrl;
}
- (NSString*) downloadAllUrl {
  return result.downloadAllUrl;
}
- (GetConfigResponse_Builder*) setDownloadAllUrl:(NSString*) value {
  result.hasDownloadAllUrl = YES;
  result.downloadAllUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearDownloadAllUrl {
  result.hasDownloadAllUrl = NO;
  result.downloadAllUrl = @"";
  return self;
}
- (BOOL) hasGetUserCloudSummaryUrl {
  return result.hasGetUserCloudSummaryUrl;
}
- (NSString*) getUserCloudSummaryUrl {
  return result.getUserCloudSummaryUrl;
}
- (GetConfigResponse_Builder*) setGetUserCloudSummaryUrl:(NSString*) value {
  result.hasGetUserCloudSummaryUrl = YES;
  result.getUserCloudSummaryUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearGetUserCloudSummaryUrl {
  result.hasGetUserCloudSummaryUrl = NO;
  result.getUserCloudSummaryUrl = @"";
  return self;
}
- (BOOL) hasQueryClientVersionUrl {
  return result.hasQueryClientVersionUrl;
}
- (NSString*) queryClientVersionUrl {
  return result.queryClientVersionUrl;
}
- (GetConfigResponse_Builder*) setQueryClientVersionUrl:(NSString*) value {
  result.hasQueryClientVersionUrl = YES;
  result.queryClientVersionUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearQueryClientVersionUrl {
  result.hasQueryClientVersionUrl = NO;
  result.queryClientVersionUrl = @"";
  return self;
}
- (BOOL) hasQueryMobileNoUrl {
  return result.hasQueryMobileNoUrl;
}
- (NSString*) queryMobileNoUrl {
  return result.queryMobileNoUrl;
}
- (GetConfigResponse_Builder*) setQueryMobileNoUrl:(NSString*) value {
  result.hasQueryMobileNoUrl = YES;
  result.queryMobileNoUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearQueryMobileNoUrl {
  result.hasQueryMobileNoUrl = NO;
  result.queryMobileNoUrl = @"";
  return self;
}
- (BOOL) hasGetSplashUrl {
  return result.hasGetSplashUrl;
}
- (NSString*) getSplashUrl {
  return result.getSplashUrl;
}
- (GetConfigResponse_Builder*) setGetSplashUrl:(NSString*) value {
  result.hasGetSplashUrl = YES;
  result.getSplashUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearGetSplashUrl {
  result.hasGetSplashUrl = NO;
  result.getSplashUrl = @"";
  return self;
}
- (BOOL) hasGetSysMsgUrl {
  return result.hasGetSysMsgUrl;
}
- (NSString*) getSysMsgUrl {
  return result.getSysMsgUrl;
}
- (GetConfigResponse_Builder*) setGetSysMsgUrl:(NSString*) value {
  result.hasGetSysMsgUrl = YES;
  result.getSysMsgUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearGetSysMsgUrl {
  result.hasGetSysMsgUrl = NO;
  result.getSysMsgUrl = @"";
  return self;
}
- (BOOL) hasQueryPublicInfoUrl {
  return result.hasQueryPublicInfoUrl;
}
- (NSString*) queryPublicInfoUrl {
  return result.queryPublicInfoUrl;
}
- (GetConfigResponse_Builder*) setQueryPublicInfoUrl:(NSString*) value {
  result.hasQueryPublicInfoUrl = YES;
  result.queryPublicInfoUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearQueryPublicInfoUrl {
  result.hasQueryPublicInfoUrl = NO;
  result.queryPublicInfoUrl = @"";
  return self;
}
- (BOOL) hasQueryCommentsUrl {
  return result.hasQueryCommentsUrl;
}
- (NSString*) queryCommentsUrl {
  return result.queryCommentsUrl;
}
- (GetConfigResponse_Builder*) setQueryCommentsUrl:(NSString*) value {
  result.hasQueryCommentsUrl = YES;
  result.queryCommentsUrl = value;
  return self;
}
- (GetConfigResponse_Builder*) clearQueryCommentsUrl {
  result.hasQueryCommentsUrl = NO;
  result.queryCommentsUrl = @"";
  return self;
}
- (BOOL) hasUploadAllUrlV2 {
  return result.hasUploadAllUrlV2;
}
- (NSString*) uploadAllUrlV2 {
  return result.uploadAllUrlV2;
}
- (GetConfigResponse_Builder*) setUploadAllUrlV2:(NSString*) value {
  result.hasUploadAllUrlV2 = YES;
  result.uploadAllUrlV2 = value;
  return self;
}
- (GetConfigResponse_Builder*) clearUploadAllUrlV2 {
  result.hasUploadAllUrlV2 = NO;
  result.uploadAllUrlV2 = @"";
  return self;
}
@end

