// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

#import "Base_type_proto.pb.h"

@class Address;
@class Address_Builder;
@class CallLog;
@class CallLog_Builder;
@class Category;
@class Category_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class FileInfo;
@class FileInfo_Builder;
@class InitMultiUploadResponse;
@class InitMultiUploadResponse_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class Website;
@class Website_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface InitMultiUploadProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface InitMultiUploadResponse : ES_PBGeneratedMessage {
@private
  BOOL hasUploadId_:1;
  BOOL hasExpires_:1;
  NSString* uploadId;
  uint32_t expires;
}
- (BOOL) hasUploadId;
- (BOOL) hasExpires;
@property (readonly, retain) NSString* uploadId;
@property (readonly) uint32_t expires;

+ (InitMultiUploadResponse*) defaultInstance;
- (InitMultiUploadResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (InitMultiUploadResponse_Builder*) builder;
+ (InitMultiUploadResponse_Builder*) builder;
+ (InitMultiUploadResponse_Builder*) builderWithPrototype:(InitMultiUploadResponse*) prototype;
- (InitMultiUploadResponse_Builder*) toBuilder;

+ (InitMultiUploadResponse*) parseFromData:(NSData*) data;
+ (InitMultiUploadResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (InitMultiUploadResponse*) parseFromInputStream:(NSInputStream*) input;
+ (InitMultiUploadResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (InitMultiUploadResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (InitMultiUploadResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface InitMultiUploadResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  InitMultiUploadResponse* result;
}

- (InitMultiUploadResponse*) defaultInstance;

- (InitMultiUploadResponse_Builder*) clear;
- (InitMultiUploadResponse_Builder*) clone;

- (InitMultiUploadResponse*) build;
- (InitMultiUploadResponse*) buildPartial;

- (InitMultiUploadResponse_Builder*) mergeFrom:(InitMultiUploadResponse*) other;
- (InitMultiUploadResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (InitMultiUploadResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUploadId;
- (NSString*) uploadId;
- (InitMultiUploadResponse_Builder*) setUploadId:(NSString*) value;
- (InitMultiUploadResponse_Builder*) clearUploadId;

- (BOOL) hasExpires;
- (uint32_t) expires;
- (InitMultiUploadResponse_Builder*) setExpires:(uint32_t) value;
- (InitMultiUploadResponse_Builder*) clearExpires;
@end

