// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Device_sign_proto.pb.h"

@implementation DeviceSignProtoRoot
static ES_PBExtensionRegistry* extensionRegistry = nil;
+ (ES_PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [DeviceSignProtoRoot class]) {
    ES_PBMutableExtensionRegistry* registry = [ES_PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry {
}
@end

@interface DeviceSignRequest ()
@property (retain) NSString* deviceId;
@end

@implementation DeviceSignRequest

- (BOOL) hasDeviceId {
  return !!hasDeviceId_;
}
- (void) setHasDeviceId:(BOOL) value_ {
  hasDeviceId_ = !!value_;
}
@synthesize deviceId;
- (void) dealloc {
  self.deviceId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.deviceId = @"";
  }
  return self;
}
static DeviceSignRequest* defaultDeviceSignRequestInstance = nil;
+ (void) initialize {
  if (self == [DeviceSignRequest class]) {
    defaultDeviceSignRequestInstance = [[DeviceSignRequest alloc] init];
  }
}
+ (DeviceSignRequest*) defaultInstance {
  return defaultDeviceSignRequestInstance;
}
- (DeviceSignRequest*) defaultInstance {
  return defaultDeviceSignRequestInstance;
}
- (BOOL) isInitialized {
  if (!self.hasDeviceId) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output {
  if (self.hasDeviceId) {
    [output writeString:1 value:self.deviceId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasDeviceId) {
    size_ += ES_computeStringSize(1, self.deviceId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (DeviceSignRequest*) parseFromData:(NSData*) data {
  return (DeviceSignRequest*)[[[DeviceSignRequest builder] mergeFromData:data] build];
}
+ (DeviceSignRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DeviceSignRequest*)[[[DeviceSignRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DeviceSignRequest*) parseFromInputStream:(NSInputStream*) input {
  return (DeviceSignRequest*)[[[DeviceSignRequest builder] mergeFromInputStream:input] build];
}
+ (DeviceSignRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DeviceSignRequest*)[[[DeviceSignRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DeviceSignRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return (DeviceSignRequest*)[[[DeviceSignRequest builder] mergeFromCodedInputStream:input] build];
}
+ (DeviceSignRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (DeviceSignRequest*)[[[DeviceSignRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DeviceSignRequest_Builder*) builder {
  return [[[DeviceSignRequest_Builder alloc] init] autorelease];
}
+ (DeviceSignRequest_Builder*) builderWithPrototype:(DeviceSignRequest*) prototype {
  return [[DeviceSignRequest builder] mergeFrom:prototype];
}
- (DeviceSignRequest_Builder*) builder {
  return [DeviceSignRequest builder];
}
- (DeviceSignRequest_Builder*) toBuilder {
  return [DeviceSignRequest builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasDeviceId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"deviceId", self.deviceId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[DeviceSignRequest class]]) {
    return NO;
  }
  DeviceSignRequest *otherMessage = other;
  return
      self.hasDeviceId == otherMessage.hasDeviceId &&
      (!self.hasDeviceId || [self.deviceId isEqual:otherMessage.deviceId]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasDeviceId) {
    hashCode = hashCode * 31 + [self.deviceId hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface DeviceSignRequest_Builder()
@property (retain) DeviceSignRequest* result;
@end

@implementation DeviceSignRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DeviceSignRequest alloc] init] autorelease];
  }
  return self;
}
- (ES_PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DeviceSignRequest_Builder*) clear {
  self.result = [[[DeviceSignRequest alloc] init] autorelease];
  return self;
}
- (DeviceSignRequest_Builder*) clone {
  return [DeviceSignRequest builderWithPrototype:result];
}
- (DeviceSignRequest*) defaultInstance {
  return [DeviceSignRequest defaultInstance];
}
- (DeviceSignRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DeviceSignRequest*) buildPartial {
  DeviceSignRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DeviceSignRequest_Builder*) mergeFrom:(DeviceSignRequest*) other {
  if (other == [DeviceSignRequest defaultInstance]) {
    return self;
  }
  if (other.hasDeviceId) {
    [self setDeviceId:other.deviceId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DeviceSignRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[ES_PBExtensionRegistry emptyRegistry]];
}
- (DeviceSignRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  ES_PBUnknownFieldSet_Builder* unknownFields = [ES_PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setDeviceId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasDeviceId {
  return result.hasDeviceId;
}
- (NSString*) deviceId {
  return result.deviceId;
}
- (DeviceSignRequest_Builder*) setDeviceId:(NSString*) value {
  result.hasDeviceId = YES;
  result.deviceId = value;
  return self;
}
- (DeviceSignRequest_Builder*) clearDeviceId {
  result.hasDeviceId = NO;
  result.deviceId = @"";
  return self;
}
@end

