// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

@class GetUserCloudSummaryResponse;
@class GetUserCloudSummaryResponse_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GetUserCloudSummaryProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface GetUserCloudSummaryResponse : ES_PBGeneratedMessage {
@private
  BOOL hasContactCount_:1;
  BOOL hasMessageCount_:1;
  BOOL hasCallLogCount_:1;
  int32_t contactCount;
  int32_t messageCount;
  int32_t callLogCount;
}
- (BOOL) hasContactCount;
- (BOOL) hasMessageCount;
- (BOOL) hasCallLogCount;
@property (readonly) int32_t contactCount;
@property (readonly) int32_t messageCount;
@property (readonly) int32_t callLogCount;

+ (GetUserCloudSummaryResponse*) defaultInstance;
- (GetUserCloudSummaryResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (GetUserCloudSummaryResponse_Builder*) builder;
+ (GetUserCloudSummaryResponse_Builder*) builder;
+ (GetUserCloudSummaryResponse_Builder*) builderWithPrototype:(GetUserCloudSummaryResponse*) prototype;
- (GetUserCloudSummaryResponse_Builder*) toBuilder;

+ (GetUserCloudSummaryResponse*) parseFromData:(NSData*) data;
+ (GetUserCloudSummaryResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetUserCloudSummaryResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetUserCloudSummaryResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (GetUserCloudSummaryResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (GetUserCloudSummaryResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface GetUserCloudSummaryResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  GetUserCloudSummaryResponse* result;
}

- (GetUserCloudSummaryResponse*) defaultInstance;

- (GetUserCloudSummaryResponse_Builder*) clear;
- (GetUserCloudSummaryResponse_Builder*) clone;

- (GetUserCloudSummaryResponse*) build;
- (GetUserCloudSummaryResponse*) buildPartial;

- (GetUserCloudSummaryResponse_Builder*) mergeFrom:(GetUserCloudSummaryResponse*) other;
- (GetUserCloudSummaryResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (GetUserCloudSummaryResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasContactCount;
- (int32_t) contactCount;
- (GetUserCloudSummaryResponse_Builder*) setContactCount:(int32_t) value;
- (GetUserCloudSummaryResponse_Builder*) clearContactCount;

- (BOOL) hasMessageCount;
- (int32_t) messageCount;
- (GetUserCloudSummaryResponse_Builder*) setMessageCount:(int32_t) value;
- (GetUserCloudSummaryResponse_Builder*) clearMessageCount;

- (BOOL) hasCallLogCount;
- (int32_t) callLogCount;
- (GetUserCloudSummaryResponse_Builder*) setCallLogCount:(int32_t) value;
- (GetUserCloudSummaryResponse_Builder*) clearCallLogCount;
@end

