// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

@class QueryMobileNoRequest;
@class QueryMobileNoRequest_Builder;
@class QueryMobileNoResponse;
@class QueryMobileNoResponse_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface QueryMobileNoProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface QueryMobileNoRequest : ES_PBGeneratedMessage {
@private
  BOOL hasImsi_:1;
  NSString* imsi;
}
- (BOOL) hasImsi;
@property (readonly, retain) NSString* imsi;

+ (QueryMobileNoRequest*) defaultInstance;
- (QueryMobileNoRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (QueryMobileNoRequest_Builder*) builder;
+ (QueryMobileNoRequest_Builder*) builder;
+ (QueryMobileNoRequest_Builder*) builderWithPrototype:(QueryMobileNoRequest*) prototype;
- (QueryMobileNoRequest_Builder*) toBuilder;

+ (QueryMobileNoRequest*) parseFromData:(NSData*) data;
+ (QueryMobileNoRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (QueryMobileNoRequest*) parseFromInputStream:(NSInputStream*) input;
+ (QueryMobileNoRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (QueryMobileNoRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (QueryMobileNoRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface QueryMobileNoRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  QueryMobileNoRequest* result;
}

- (QueryMobileNoRequest*) defaultInstance;

- (QueryMobileNoRequest_Builder*) clear;
- (QueryMobileNoRequest_Builder*) clone;

- (QueryMobileNoRequest*) build;
- (QueryMobileNoRequest*) buildPartial;

- (QueryMobileNoRequest_Builder*) mergeFrom:(QueryMobileNoRequest*) other;
- (QueryMobileNoRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (QueryMobileNoRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasImsi;
- (NSString*) imsi;
- (QueryMobileNoRequest_Builder*) setImsi:(NSString*) value;
- (QueryMobileNoRequest_Builder*) clearImsi;
@end

@interface QueryMobileNoResponse : ES_PBGeneratedMessage {
@private
  BOOL hasMobileNum_:1;
  BOOL hasAlias_:1;
  NSString* mobileNum;
  NSString* alias;
}
- (BOOL) hasMobileNum;
- (BOOL) hasAlias;
@property (readonly, retain) NSString* mobileNum;
@property (readonly, retain) NSString* alias;

+ (QueryMobileNoResponse*) defaultInstance;
- (QueryMobileNoResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (QueryMobileNoResponse_Builder*) builder;
+ (QueryMobileNoResponse_Builder*) builder;
+ (QueryMobileNoResponse_Builder*) builderWithPrototype:(QueryMobileNoResponse*) prototype;
- (QueryMobileNoResponse_Builder*) toBuilder;

+ (QueryMobileNoResponse*) parseFromData:(NSData*) data;
+ (QueryMobileNoResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (QueryMobileNoResponse*) parseFromInputStream:(NSInputStream*) input;
+ (QueryMobileNoResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (QueryMobileNoResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (QueryMobileNoResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface QueryMobileNoResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  QueryMobileNoResponse* result;
}

- (QueryMobileNoResponse*) defaultInstance;

- (QueryMobileNoResponse_Builder*) clear;
- (QueryMobileNoResponse_Builder*) clone;

- (QueryMobileNoResponse*) build;
- (QueryMobileNoResponse*) buildPartial;

- (QueryMobileNoResponse_Builder*) mergeFrom:(QueryMobileNoResponse*) other;
- (QueryMobileNoResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (QueryMobileNoResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMobileNum;
- (NSString*) mobileNum;
- (QueryMobileNoResponse_Builder*) setMobileNum:(NSString*) value;
- (QueryMobileNoResponse_Builder*) clearMobileNum;

- (BOOL) hasAlias;
- (NSString*) alias;
- (QueryMobileNoResponse_Builder*) setAlias:(NSString*) value;
- (QueryMobileNoResponse_Builder*) clearAlias;
@end

