// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

#import "Base_type_proto.pb.h"

@class Address;
@class Address_Builder;
@class Category;
@class Category_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class UploadSmsRequest;
@class UploadSmsRequest_Builder;
@class Website;
@class Website_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface UploadSmsProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface UploadSmsRequest : ES_PBGeneratedMessage {
@private
  ES_PBAppendableArray * smsArray;
}
@property (readonly, retain) ES_PBArray * sms;
- (Sms*)smsAtIndex:(NSUInteger)index;

+ (UploadSmsRequest*) defaultInstance;
- (UploadSmsRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (UploadSmsRequest_Builder*) builder;
+ (UploadSmsRequest_Builder*) builder;
+ (UploadSmsRequest_Builder*) builderWithPrototype:(UploadSmsRequest*) prototype;
- (UploadSmsRequest_Builder*) toBuilder;

+ (UploadSmsRequest*) parseFromData:(NSData*) data;
+ (UploadSmsRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (UploadSmsRequest*) parseFromInputStream:(NSInputStream*) input;
+ (UploadSmsRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (UploadSmsRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (UploadSmsRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadSmsRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  UploadSmsRequest* result;
}

- (UploadSmsRequest*) defaultInstance;

- (UploadSmsRequest_Builder*) clear;
- (UploadSmsRequest_Builder*) clone;

- (UploadSmsRequest*) build;
- (UploadSmsRequest*) buildPartial;

- (UploadSmsRequest_Builder*) mergeFrom:(UploadSmsRequest*) other;
- (UploadSmsRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (UploadSmsRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (ES_PBAppendableArray *)sms;
- (Sms*)smsAtIndex:(NSUInteger)index;
- (UploadSmsRequest_Builder *)addSms:(Sms*)value;
- (UploadSmsRequest_Builder *)setSmsArray:(NSArray *)array;
- (UploadSmsRequest_Builder *)setSmsValues:(const Sms* *)values count:(NSUInteger)count;
- (UploadSmsRequest_Builder *)clearSms;
@end

