// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Upload_sms_proto.pb.h"

@implementation UploadSmsProtoRoot
static ES_PBExtensionRegistry* extensionRegistry = nil;
+ (ES_PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UploadSmsProtoRoot class]) {
    ES_PBMutableExtensionRegistry* registry = [ES_PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [BaseTypeProtoRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry {
}
@end

@interface UploadSmsRequest ()
@property (retain) ES_PBAppendableArray * smsArray;
@end

@implementation UploadSmsRequest

@synthesize smsArray;
@dynamic sms;
- (void) dealloc {
  self.smsArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static UploadSmsRequest* defaultUploadSmsRequestInstance = nil;
+ (void) initialize {
  if (self == [UploadSmsRequest class]) {
    defaultUploadSmsRequestInstance = [[UploadSmsRequest alloc] init];
  }
}
+ (UploadSmsRequest*) defaultInstance {
  return defaultUploadSmsRequestInstance;
}
- (UploadSmsRequest*) defaultInstance {
  return defaultUploadSmsRequestInstance;
}
- (ES_PBArray *)sms {
  return smsArray;
}
- (Sms*)smsAtIndex:(NSUInteger)index {
  return [smsArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  for (Sms* element in self.sms) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output {
  for (Sms *element in self.smsArray) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  for (Sms *element in self.smsArray) {
    size_ += ES_computeMessageSize(1, element);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UploadSmsRequest*) parseFromData:(NSData*) data {
  return (UploadSmsRequest*)[[[UploadSmsRequest builder] mergeFromData:data] build];
}
+ (UploadSmsRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadSmsRequest*)[[[UploadSmsRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UploadSmsRequest*) parseFromInputStream:(NSInputStream*) input {
  return (UploadSmsRequest*)[[[UploadSmsRequest builder] mergeFromInputStream:input] build];
}
+ (UploadSmsRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadSmsRequest*)[[[UploadSmsRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UploadSmsRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return (UploadSmsRequest*)[[[UploadSmsRequest builder] mergeFromCodedInputStream:input] build];
}
+ (UploadSmsRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadSmsRequest*)[[[UploadSmsRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UploadSmsRequest_Builder*) builder {
  return [[[UploadSmsRequest_Builder alloc] init] autorelease];
}
+ (UploadSmsRequest_Builder*) builderWithPrototype:(UploadSmsRequest*) prototype {
  return [[UploadSmsRequest builder] mergeFrom:prototype];
}
- (UploadSmsRequest_Builder*) builder {
  return [UploadSmsRequest builder];
}
- (UploadSmsRequest_Builder*) toBuilder {
  return [UploadSmsRequest builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  for (Sms* element in self.smsArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"sms"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UploadSmsRequest class]]) {
    return NO;
  }
  UploadSmsRequest *otherMessage = other;
  return
      [self.smsArray isEqualToArray:otherMessage.smsArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  for (Sms* element in self.smsArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UploadSmsRequest_Builder()
@property (retain) UploadSmsRequest* result;
@end

@implementation UploadSmsRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[UploadSmsRequest alloc] init] autorelease];
  }
  return self;
}
- (ES_PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UploadSmsRequest_Builder*) clear {
  self.result = [[[UploadSmsRequest alloc] init] autorelease];
  return self;
}
- (UploadSmsRequest_Builder*) clone {
  return [UploadSmsRequest builderWithPrototype:result];
}
- (UploadSmsRequest*) defaultInstance {
  return [UploadSmsRequest defaultInstance];
}
- (UploadSmsRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UploadSmsRequest*) buildPartial {
  UploadSmsRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (UploadSmsRequest_Builder*) mergeFrom:(UploadSmsRequest*) other {
  if (other == [UploadSmsRequest defaultInstance]) {
    return self;
  }
  if (other.smsArray.count > 0) {
    if (result.smsArray == nil) {
      result.smsArray = [[other.smsArray copyWithZone:[other.smsArray zone]] autorelease];
    } else {
      [result.smsArray appendArray:other.smsArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UploadSmsRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[ES_PBExtensionRegistry emptyRegistry]];
}
- (UploadSmsRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  ES_PBUnknownFieldSet_Builder* unknownFields = [ES_PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        Sms_Builder* subBuilder = [Sms builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addSms:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (ES_PBAppendableArray *)sms {
  return result.smsArray;
}
- (Sms*)smsAtIndex:(NSUInteger)index {
  return [result smsAtIndex:index];
}
- (UploadSmsRequest_Builder *)addSms:(Sms*)value {
  if (result.smsArray == nil) {
    result.smsArray = [ES_PBAppendableArray arrayWithValueType:ES_PBArrayValueTypeObject];
  }
  [result.smsArray addObject:value];
  return self;
}
- (UploadSmsRequest_Builder *)setSmsArray:(NSArray *)array {
  result.smsArray = [ES_PBAppendableArray arrayWithArray:array valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadSmsRequest_Builder *)setSmsValues:(const Sms* *)values count:(NSUInteger)count {
  result.smsArray = [ES_PBAppendableArray arrayWithValues:values count:count valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadSmsRequest_Builder *)clearSms {
  result.smsArray = nil;
  return self;
}
@end

