// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

#import "Base_type_proto.pb.h"

@class Address;
@class Address_Builder;
@class Category;
@class Category_Builder;
@class DownloadPortraitData;
@class DownloadPortraitData_Builder;
@class DownloadPortraitRequest;
@class DownloadPortraitRequest_Builder;
@class DownloadPortraitResponse;
@class DownloadPortraitResponse_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class Website;
@class Website_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface DownloadPortraitProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface DownloadPortraitRequest : ES_PBGeneratedMessage {
@private
  BOOL hasIsRequestBusinessCardPortrait_:1;
  BOOL isRequestBusinessCardPortrait_:1;
  ES_PBAppendableArray * sidArray;
  int32_t sidMemoizedSerializedSize;
}
- (BOOL) hasIsRequestBusinessCardPortrait;
@property (readonly, retain) ES_PBArray * sid;
- (BOOL) isRequestBusinessCardPortrait;
- (int32_t)sidAtIndex:(NSUInteger)index;

+ (DownloadPortraitRequest*) defaultInstance;
- (DownloadPortraitRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (DownloadPortraitRequest_Builder*) builder;
+ (DownloadPortraitRequest_Builder*) builder;
+ (DownloadPortraitRequest_Builder*) builderWithPrototype:(DownloadPortraitRequest*) prototype;
- (DownloadPortraitRequest_Builder*) toBuilder;

+ (DownloadPortraitRequest*) parseFromData:(NSData*) data;
+ (DownloadPortraitRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (DownloadPortraitRequest*) parseFromInputStream:(NSInputStream*) input;
+ (DownloadPortraitRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (DownloadPortraitRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (DownloadPortraitRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface DownloadPortraitRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  DownloadPortraitRequest* result;
}

- (DownloadPortraitRequest*) defaultInstance;

- (DownloadPortraitRequest_Builder*) clear;
- (DownloadPortraitRequest_Builder*) clone;

- (DownloadPortraitRequest*) build;
- (DownloadPortraitRequest*) buildPartial;

- (DownloadPortraitRequest_Builder*) mergeFrom:(DownloadPortraitRequest*) other;
- (DownloadPortraitRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (DownloadPortraitRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (ES_PBAppendableArray *)sid;
- (int32_t)sidAtIndex:(NSUInteger)index;
- (DownloadPortraitRequest_Builder *)addSid:(int32_t)value;
- (DownloadPortraitRequest_Builder *)setSidArray:(NSArray *)array;
- (DownloadPortraitRequest_Builder *)setSidValues:(const int32_t *)values count:(NSUInteger)count;
- (DownloadPortraitRequest_Builder *)clearSid;

- (BOOL) hasIsRequestBusinessCardPortrait;
- (BOOL) isRequestBusinessCardPortrait;
- (DownloadPortraitRequest_Builder*) setIsRequestBusinessCardPortrait:(BOOL) value;
- (DownloadPortraitRequest_Builder*) clearIsRequestBusinessCardPortrait;
@end

@interface DownloadPortraitData : ES_PBGeneratedMessage {
@private
  BOOL hasPortraitVersion_:1;
  BOOL hasPortraitData_:1;
  int32_t portraitVersion;
  PortraitData* portraitData;
}
- (BOOL) hasPortraitData;
- (BOOL) hasPortraitVersion;
@property (readonly, retain) PortraitData* portraitData;
@property (readonly) int32_t portraitVersion;

+ (DownloadPortraitData*) defaultInstance;
- (DownloadPortraitData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (DownloadPortraitData_Builder*) builder;
+ (DownloadPortraitData_Builder*) builder;
+ (DownloadPortraitData_Builder*) builderWithPrototype:(DownloadPortraitData*) prototype;
- (DownloadPortraitData_Builder*) toBuilder;

+ (DownloadPortraitData*) parseFromData:(NSData*) data;
+ (DownloadPortraitData*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (DownloadPortraitData*) parseFromInputStream:(NSInputStream*) input;
+ (DownloadPortraitData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (DownloadPortraitData*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (DownloadPortraitData*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface DownloadPortraitData_Builder : ES_PBGeneratedMessage_Builder {
@private
  DownloadPortraitData* result;
}

- (DownloadPortraitData*) defaultInstance;

- (DownloadPortraitData_Builder*) clear;
- (DownloadPortraitData_Builder*) clone;

- (DownloadPortraitData*) build;
- (DownloadPortraitData*) buildPartial;

- (DownloadPortraitData_Builder*) mergeFrom:(DownloadPortraitData*) other;
- (DownloadPortraitData_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (DownloadPortraitData_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPortraitData;
- (PortraitData*) portraitData;
- (DownloadPortraitData_Builder*) setPortraitData:(PortraitData*) value;
- (DownloadPortraitData_Builder*) setPortraitDataBuilder:(PortraitData_Builder*) builderForValue;
- (DownloadPortraitData_Builder*) mergePortraitData:(PortraitData*) value;
- (DownloadPortraitData_Builder*) clearPortraitData;

- (BOOL) hasPortraitVersion;
- (int32_t) portraitVersion;
- (DownloadPortraitData_Builder*) setPortraitVersion:(int32_t) value;
- (DownloadPortraitData_Builder*) clearPortraitVersion;
@end

@interface DownloadPortraitResponse : ES_PBGeneratedMessage {
@private
  BOOL hasBusinessCardPortrait_:1;
  DownloadPortraitData* businessCardPortrait;
  ES_PBAppendableArray * portraitArray;
}
- (BOOL) hasBusinessCardPortrait;
@property (readonly, retain) ES_PBArray * portrait;
@property (readonly, retain) DownloadPortraitData* businessCardPortrait;
- (DownloadPortraitData*)portraitAtIndex:(NSUInteger)index;

+ (DownloadPortraitResponse*) defaultInstance;
- (DownloadPortraitResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (DownloadPortraitResponse_Builder*) builder;
+ (DownloadPortraitResponse_Builder*) builder;
+ (DownloadPortraitResponse_Builder*) builderWithPrototype:(DownloadPortraitResponse*) prototype;
- (DownloadPortraitResponse_Builder*) toBuilder;

+ (DownloadPortraitResponse*) parseFromData:(NSData*) data;
+ (DownloadPortraitResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (DownloadPortraitResponse*) parseFromInputStream:(NSInputStream*) input;
+ (DownloadPortraitResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (DownloadPortraitResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (DownloadPortraitResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface DownloadPortraitResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  DownloadPortraitResponse* result;
}

- (DownloadPortraitResponse*) defaultInstance;

- (DownloadPortraitResponse_Builder*) clear;
- (DownloadPortraitResponse_Builder*) clone;

- (DownloadPortraitResponse*) build;
- (DownloadPortraitResponse*) buildPartial;

- (DownloadPortraitResponse_Builder*) mergeFrom:(DownloadPortraitResponse*) other;
- (DownloadPortraitResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (DownloadPortraitResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (ES_PBAppendableArray *)portrait;
- (DownloadPortraitData*)portraitAtIndex:(NSUInteger)index;
- (DownloadPortraitResponse_Builder *)addPortrait:(DownloadPortraitData*)value;
- (DownloadPortraitResponse_Builder *)setPortraitArray:(NSArray *)array;
- (DownloadPortraitResponse_Builder *)setPortraitValues:(const DownloadPortraitData* *)values count:(NSUInteger)count;
- (DownloadPortraitResponse_Builder *)clearPortrait;

- (BOOL) hasBusinessCardPortrait;
- (DownloadPortraitData*) businessCardPortrait;
- (DownloadPortraitResponse_Builder*) setBusinessCardPortrait:(DownloadPortraitData*) value;
- (DownloadPortraitResponse_Builder*) setBusinessCardPortraitBuilder:(DownloadPortraitData_Builder*) builderForValue;
- (DownloadPortraitResponse_Builder*) mergeBusinessCardPortrait:(DownloadPortraitData*) value;
- (DownloadPortraitResponse_Builder*) clearBusinessCardPortrait;
@end

