// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

@class ClientReportRequest;
@class ClientReportRequest_Builder;
@class ErrorReport;
@class ErrorReport_Builder;
@class ObsoleteClientReportRequest;
@class ObsoleteClientReportRequest_Builder;
@class ObsoleteErrorReport;
@class ObsoleteErrorReport_Builder;
@class PlainClientReportRequest;
@class PlainClientReportRequest_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ClientReportProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface ObsoleteErrorReport : ES_PBGeneratedMessage {
@private
  BOOL hasTotalMemSize_:1;
  BOOL hasAvailableMemSize_:1;
  BOOL hasReportId_:1;
  BOOL hasAppVersionCode_:1;
  BOOL hasAppVersionName_:1;
  BOOL hasPhoneModel_:1;
  BOOL hasBrand_:1;
  BOOL hasProduct_:1;
  BOOL hasOsVersion_:1;
  BOOL hasStackTrace_:1;
  BOOL hasUserAppStartTime_:1;
  BOOL hasUserAppCrashTime_:1;
  int32_t totalMemSize;
  int32_t availableMemSize;
  NSString* reportId;
  NSString* appVersionCode;
  NSString* appVersionName;
  NSString* phoneModel;
  NSString* brand;
  NSString* product;
  NSString* osVersion;
  NSString* stackTrace;
  NSString* userAppStartTime;
  NSString* userAppCrashTime;
}
- (BOOL) hasReportId;
- (BOOL) hasAppVersionCode;
- (BOOL) hasAppVersionName;
- (BOOL) hasPhoneModel;
- (BOOL) hasBrand;
- (BOOL) hasProduct;
- (BOOL) hasOsVersion;
- (BOOL) hasTotalMemSize;
- (BOOL) hasAvailableMemSize;
- (BOOL) hasStackTrace;
- (BOOL) hasUserAppStartTime;
- (BOOL) hasUserAppCrashTime;
@property (readonly, retain) NSString* reportId;
@property (readonly, retain) NSString* appVersionCode;
@property (readonly, retain) NSString* appVersionName;
@property (readonly, retain) NSString* phoneModel;
@property (readonly, retain) NSString* brand;
@property (readonly, retain) NSString* product;
@property (readonly, retain) NSString* osVersion;
@property (readonly) int32_t totalMemSize;
@property (readonly) int32_t availableMemSize;
@property (readonly, retain) NSString* stackTrace;
@property (readonly, retain) NSString* userAppStartTime;
@property (readonly, retain) NSString* userAppCrashTime;

+ (ObsoleteErrorReport*) defaultInstance;
- (ObsoleteErrorReport*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (ObsoleteErrorReport_Builder*) builder;
+ (ObsoleteErrorReport_Builder*) builder;
+ (ObsoleteErrorReport_Builder*) builderWithPrototype:(ObsoleteErrorReport*) prototype;
- (ObsoleteErrorReport_Builder*) toBuilder;

+ (ObsoleteErrorReport*) parseFromData:(NSData*) data;
+ (ObsoleteErrorReport*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ObsoleteErrorReport*) parseFromInputStream:(NSInputStream*) input;
+ (ObsoleteErrorReport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ObsoleteErrorReport*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (ObsoleteErrorReport*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface ObsoleteErrorReport_Builder : ES_PBGeneratedMessage_Builder {
@private
  ObsoleteErrorReport* result;
}

- (ObsoleteErrorReport*) defaultInstance;

- (ObsoleteErrorReport_Builder*) clear;
- (ObsoleteErrorReport_Builder*) clone;

- (ObsoleteErrorReport*) build;
- (ObsoleteErrorReport*) buildPartial;

- (ObsoleteErrorReport_Builder*) mergeFrom:(ObsoleteErrorReport*) other;
- (ObsoleteErrorReport_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (ObsoleteErrorReport_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasReportId;
- (NSString*) reportId;
- (ObsoleteErrorReport_Builder*) setReportId:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearReportId;

- (BOOL) hasAppVersionCode;
- (NSString*) appVersionCode;
- (ObsoleteErrorReport_Builder*) setAppVersionCode:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearAppVersionCode;

- (BOOL) hasAppVersionName;
- (NSString*) appVersionName;
- (ObsoleteErrorReport_Builder*) setAppVersionName:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearAppVersionName;

- (BOOL) hasPhoneModel;
- (NSString*) phoneModel;
- (ObsoleteErrorReport_Builder*) setPhoneModel:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearPhoneModel;

- (BOOL) hasBrand;
- (NSString*) brand;
- (ObsoleteErrorReport_Builder*) setBrand:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearBrand;

- (BOOL) hasProduct;
- (NSString*) product;
- (ObsoleteErrorReport_Builder*) setProduct:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearProduct;

- (BOOL) hasOsVersion;
- (NSString*) osVersion;
- (ObsoleteErrorReport_Builder*) setOsVersion:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearOsVersion;

- (BOOL) hasTotalMemSize;
- (int32_t) totalMemSize;
- (ObsoleteErrorReport_Builder*) setTotalMemSize:(int32_t) value;
- (ObsoleteErrorReport_Builder*) clearTotalMemSize;

- (BOOL) hasAvailableMemSize;
- (int32_t) availableMemSize;
- (ObsoleteErrorReport_Builder*) setAvailableMemSize:(int32_t) value;
- (ObsoleteErrorReport_Builder*) clearAvailableMemSize;

- (BOOL) hasStackTrace;
- (NSString*) stackTrace;
- (ObsoleteErrorReport_Builder*) setStackTrace:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearStackTrace;

- (BOOL) hasUserAppStartTime;
- (NSString*) userAppStartTime;
- (ObsoleteErrorReport_Builder*) setUserAppStartTime:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearUserAppStartTime;

- (BOOL) hasUserAppCrashTime;
- (NSString*) userAppCrashTime;
- (ObsoleteErrorReport_Builder*) setUserAppCrashTime:(NSString*) value;
- (ObsoleteErrorReport_Builder*) clearUserAppCrashTime;
@end

@interface ErrorReport : ES_PBGeneratedMessage {
@private
  BOOL hasTotalMemSize_:1;
  BOOL hasAvailableMemSize_:1;
  BOOL hasReportId_:1;
  BOOL hasAppVersionCode_:1;
  BOOL hasAppVersionName_:1;
  BOOL hasPhoneModel_:1;
  BOOL hasBrand_:1;
  BOOL hasProduct_:1;
  BOOL hasOsVersion_:1;
  BOOL hasStackTrace_:1;
  BOOL hasUserAppStartTime_:1;
  BOOL hasUserAppCrashTime_:1;
  int64_t totalMemSize;
  int64_t availableMemSize;
  NSString* reportId;
  NSString* appVersionCode;
  NSString* appVersionName;
  NSString* phoneModel;
  NSString* brand;
  NSString* product;
  NSString* osVersion;
  NSString* stackTrace;
  NSString* userAppStartTime;
  NSString* userAppCrashTime;
}
- (BOOL) hasReportId;
- (BOOL) hasAppVersionCode;
- (BOOL) hasAppVersionName;
- (BOOL) hasPhoneModel;
- (BOOL) hasBrand;
- (BOOL) hasProduct;
- (BOOL) hasOsVersion;
- (BOOL) hasTotalMemSize;
- (BOOL) hasAvailableMemSize;
- (BOOL) hasStackTrace;
- (BOOL) hasUserAppStartTime;
- (BOOL) hasUserAppCrashTime;
@property (readonly, retain) NSString* reportId;
@property (readonly, retain) NSString* appVersionCode;
@property (readonly, retain) NSString* appVersionName;
@property (readonly, retain) NSString* phoneModel;
@property (readonly, retain) NSString* brand;
@property (readonly, retain) NSString* product;
@property (readonly, retain) NSString* osVersion;
@property (readonly) int64_t totalMemSize;
@property (readonly) int64_t availableMemSize;
@property (readonly, retain) NSString* stackTrace;
@property (readonly, retain) NSString* userAppStartTime;
@property (readonly, retain) NSString* userAppCrashTime;

+ (ErrorReport*) defaultInstance;
- (ErrorReport*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (ErrorReport_Builder*) builder;
+ (ErrorReport_Builder*) builder;
+ (ErrorReport_Builder*) builderWithPrototype:(ErrorReport*) prototype;
- (ErrorReport_Builder*) toBuilder;

+ (ErrorReport*) parseFromData:(NSData*) data;
+ (ErrorReport*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ErrorReport*) parseFromInputStream:(NSInputStream*) input;
+ (ErrorReport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ErrorReport*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (ErrorReport*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface ErrorReport_Builder : ES_PBGeneratedMessage_Builder {
@private
  ErrorReport* result;
}

- (ErrorReport*) defaultInstance;

- (ErrorReport_Builder*) clear;
- (ErrorReport_Builder*) clone;

- (ErrorReport*) build;
- (ErrorReport*) buildPartial;

- (ErrorReport_Builder*) mergeFrom:(ErrorReport*) other;
- (ErrorReport_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (ErrorReport_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasReportId;
- (NSString*) reportId;
- (ErrorReport_Builder*) setReportId:(NSString*) value;
- (ErrorReport_Builder*) clearReportId;

- (BOOL) hasAppVersionCode;
- (NSString*) appVersionCode;
- (ErrorReport_Builder*) setAppVersionCode:(NSString*) value;
- (ErrorReport_Builder*) clearAppVersionCode;

- (BOOL) hasAppVersionName;
- (NSString*) appVersionName;
- (ErrorReport_Builder*) setAppVersionName:(NSString*) value;
- (ErrorReport_Builder*) clearAppVersionName;

- (BOOL) hasPhoneModel;
- (NSString*) phoneModel;
- (ErrorReport_Builder*) setPhoneModel:(NSString*) value;
- (ErrorReport_Builder*) clearPhoneModel;

- (BOOL) hasBrand;
- (NSString*) brand;
- (ErrorReport_Builder*) setBrand:(NSString*) value;
- (ErrorReport_Builder*) clearBrand;

- (BOOL) hasProduct;
- (NSString*) product;
- (ErrorReport_Builder*) setProduct:(NSString*) value;
- (ErrorReport_Builder*) clearProduct;

- (BOOL) hasOsVersion;
- (NSString*) osVersion;
- (ErrorReport_Builder*) setOsVersion:(NSString*) value;
- (ErrorReport_Builder*) clearOsVersion;

- (BOOL) hasTotalMemSize;
- (int64_t) totalMemSize;
- (ErrorReport_Builder*) setTotalMemSize:(int64_t) value;
- (ErrorReport_Builder*) clearTotalMemSize;

- (BOOL) hasAvailableMemSize;
- (int64_t) availableMemSize;
- (ErrorReport_Builder*) setAvailableMemSize:(int64_t) value;
- (ErrorReport_Builder*) clearAvailableMemSize;

- (BOOL) hasStackTrace;
- (NSString*) stackTrace;
- (ErrorReport_Builder*) setStackTrace:(NSString*) value;
- (ErrorReport_Builder*) clearStackTrace;

- (BOOL) hasUserAppStartTime;
- (NSString*) userAppStartTime;
- (ErrorReport_Builder*) setUserAppStartTime:(NSString*) value;
- (ErrorReport_Builder*) clearUserAppStartTime;

- (BOOL) hasUserAppCrashTime;
- (NSString*) userAppCrashTime;
- (ErrorReport_Builder*) setUserAppCrashTime:(NSString*) value;
- (ErrorReport_Builder*) clearUserAppCrashTime;
@end

@interface ObsoleteClientReportRequest : ES_PBGeneratedMessage {
@private
  BOOL hasSyncUserId_:1;
  BOOL hasImsi_:1;
  BOOL hasSurfingAccount_:1;
  int64_t syncUserId;
  NSString* imsi;
  NSString* surfingAccount;
  ES_PBAppendableArray * errorReportArray;
}
- (BOOL) hasImsi;
- (BOOL) hasSurfingAccount;
- (BOOL) hasSyncUserId;
@property (readonly, retain) NSString* imsi;
@property (readonly, retain) NSString* surfingAccount;
@property (readonly) int64_t syncUserId;
@property (readonly, retain) ES_PBArray * errorReport;
- (ObsoleteErrorReport*)errorReportAtIndex:(NSUInteger)index;

+ (ObsoleteClientReportRequest*) defaultInstance;
- (ObsoleteClientReportRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (ObsoleteClientReportRequest_Builder*) builder;
+ (ObsoleteClientReportRequest_Builder*) builder;
+ (ObsoleteClientReportRequest_Builder*) builderWithPrototype:(ObsoleteClientReportRequest*) prototype;
- (ObsoleteClientReportRequest_Builder*) toBuilder;

+ (ObsoleteClientReportRequest*) parseFromData:(NSData*) data;
+ (ObsoleteClientReportRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ObsoleteClientReportRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ObsoleteClientReportRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ObsoleteClientReportRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (ObsoleteClientReportRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface ObsoleteClientReportRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  ObsoleteClientReportRequest* result;
}

- (ObsoleteClientReportRequest*) defaultInstance;

- (ObsoleteClientReportRequest_Builder*) clear;
- (ObsoleteClientReportRequest_Builder*) clone;

- (ObsoleteClientReportRequest*) build;
- (ObsoleteClientReportRequest*) buildPartial;

- (ObsoleteClientReportRequest_Builder*) mergeFrom:(ObsoleteClientReportRequest*) other;
- (ObsoleteClientReportRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (ObsoleteClientReportRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasImsi;
- (NSString*) imsi;
- (ObsoleteClientReportRequest_Builder*) setImsi:(NSString*) value;
- (ObsoleteClientReportRequest_Builder*) clearImsi;

- (BOOL) hasSurfingAccount;
- (NSString*) surfingAccount;
- (ObsoleteClientReportRequest_Builder*) setSurfingAccount:(NSString*) value;
- (ObsoleteClientReportRequest_Builder*) clearSurfingAccount;

- (BOOL) hasSyncUserId;
- (int64_t) syncUserId;
- (ObsoleteClientReportRequest_Builder*) setSyncUserId:(int64_t) value;
- (ObsoleteClientReportRequest_Builder*) clearSyncUserId;

- (ES_PBAppendableArray *)errorReport;
- (ObsoleteErrorReport*)errorReportAtIndex:(NSUInteger)index;
- (ObsoleteClientReportRequest_Builder *)addErrorReport:(ObsoleteErrorReport*)value;
- (ObsoleteClientReportRequest_Builder *)setErrorReportArray:(NSArray *)array;
- (ObsoleteClientReportRequest_Builder *)setErrorReportValues:(const ObsoleteErrorReport* *)values count:(NSUInteger)count;
- (ObsoleteClientReportRequest_Builder *)clearErrorReport;
@end

@interface ClientReportRequest : ES_PBGeneratedMessage {
@private
  BOOL hasSyncUserId_:1;
  BOOL hasImsi_:1;
  BOOL hasSurfingAccount_:1;
  int64_t syncUserId;
  NSString* imsi;
  NSString* surfingAccount;
  ES_PBAppendableArray * errorReportArray;
}
- (BOOL) hasImsi;
- (BOOL) hasSurfingAccount;
- (BOOL) hasSyncUserId;
@property (readonly, retain) NSString* imsi;
@property (readonly, retain) NSString* surfingAccount;
@property (readonly) int64_t syncUserId;
@property (readonly, retain) ES_PBArray * errorReport;
- (ErrorReport*)errorReportAtIndex:(NSUInteger)index;

+ (ClientReportRequest*) defaultInstance;
- (ClientReportRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (ClientReportRequest_Builder*) builder;
+ (ClientReportRequest_Builder*) builder;
+ (ClientReportRequest_Builder*) builderWithPrototype:(ClientReportRequest*) prototype;
- (ClientReportRequest_Builder*) toBuilder;

+ (ClientReportRequest*) parseFromData:(NSData*) data;
+ (ClientReportRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ClientReportRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ClientReportRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (ClientReportRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (ClientReportRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface ClientReportRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  ClientReportRequest* result;
}

- (ClientReportRequest*) defaultInstance;

- (ClientReportRequest_Builder*) clear;
- (ClientReportRequest_Builder*) clone;

- (ClientReportRequest*) build;
- (ClientReportRequest*) buildPartial;

- (ClientReportRequest_Builder*) mergeFrom:(ClientReportRequest*) other;
- (ClientReportRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (ClientReportRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasImsi;
- (NSString*) imsi;
- (ClientReportRequest_Builder*) setImsi:(NSString*) value;
- (ClientReportRequest_Builder*) clearImsi;

- (BOOL) hasSurfingAccount;
- (NSString*) surfingAccount;
- (ClientReportRequest_Builder*) setSurfingAccount:(NSString*) value;
- (ClientReportRequest_Builder*) clearSurfingAccount;

- (BOOL) hasSyncUserId;
- (int64_t) syncUserId;
- (ClientReportRequest_Builder*) setSyncUserId:(int64_t) value;
- (ClientReportRequest_Builder*) clearSyncUserId;

- (ES_PBAppendableArray *)errorReport;
- (ErrorReport*)errorReportAtIndex:(NSUInteger)index;
- (ClientReportRequest_Builder *)addErrorReport:(ErrorReport*)value;
- (ClientReportRequest_Builder *)setErrorReportArray:(NSArray *)array;
- (ClientReportRequest_Builder *)setErrorReportValues:(const ErrorReport* *)values count:(NSUInteger)count;
- (ClientReportRequest_Builder *)clearErrorReport;
@end

@interface PlainClientReportRequest : ES_PBGeneratedMessage {
@private
  BOOL hasMobileNo_:1;
  BOOL hasPlainTrace_:1;
  NSString* mobileNo;
  NSData* plainTrace;
}
- (BOOL) hasMobileNo;
- (BOOL) hasPlainTrace;
@property (readonly, retain) NSString* mobileNo;
@property (readonly, retain) NSData* plainTrace;

+ (PlainClientReportRequest*) defaultInstance;
- (PlainClientReportRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (PlainClientReportRequest_Builder*) builder;
+ (PlainClientReportRequest_Builder*) builder;
+ (PlainClientReportRequest_Builder*) builderWithPrototype:(PlainClientReportRequest*) prototype;
- (PlainClientReportRequest_Builder*) toBuilder;

+ (PlainClientReportRequest*) parseFromData:(NSData*) data;
+ (PlainClientReportRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (PlainClientReportRequest*) parseFromInputStream:(NSInputStream*) input;
+ (PlainClientReportRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (PlainClientReportRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (PlainClientReportRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface PlainClientReportRequest_Builder : ES_PBGeneratedMessage_Builder {
@private
  PlainClientReportRequest* result;
}

- (PlainClientReportRequest*) defaultInstance;

- (PlainClientReportRequest_Builder*) clear;
- (PlainClientReportRequest_Builder*) clone;

- (PlainClientReportRequest*) build;
- (PlainClientReportRequest*) buildPartial;

- (PlainClientReportRequest_Builder*) mergeFrom:(PlainClientReportRequest*) other;
- (PlainClientReportRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (PlainClientReportRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMobileNo;
- (NSString*) mobileNo;
- (PlainClientReportRequest_Builder*) setMobileNo:(NSString*) value;
- (PlainClientReportRequest_Builder*) clearMobileNo;

- (BOOL) hasPlainTrace;
- (NSData*) plainTrace;
- (PlainClientReportRequest_Builder*) setPlainTrace:(NSData*) value;
- (PlainClientReportRequest_Builder*) clearPlainTrace;
@end

