// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ES_ProtocolBuffers.h"

#import "Base_type_proto.pb.h"

@class Address;
@class Address_Builder;
@class CallLog;
@class CallLog_Builder;
@class Category;
@class Category_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class FileInfo;
@class FileInfo_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class RecoverCallLogResponse;
@class RecoverCallLogResponse_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class Website;
@class Website_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface RecoverCalllogProtoRoot : NSObject {
}
+ (ES_PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry;
@end

@interface RecoverCallLogResponse : ES_PBGeneratedMessage {
@private
  ES_PBAppendableArray * callLogArray;
}
@property (readonly, retain) ES_PBArray * callLog;
- (CallLog*)callLogAtIndex:(NSUInteger)index;

+ (RecoverCallLogResponse*) defaultInstance;
- (RecoverCallLogResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output;
- (RecoverCallLogResponse_Builder*) builder;
+ (RecoverCallLogResponse_Builder*) builder;
+ (RecoverCallLogResponse_Builder*) builderWithPrototype:(RecoverCallLogResponse*) prototype;
- (RecoverCallLogResponse_Builder*) toBuilder;

+ (RecoverCallLogResponse*) parseFromData:(NSData*) data;
+ (RecoverCallLogResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (RecoverCallLogResponse*) parseFromInputStream:(NSInputStream*) input;
+ (RecoverCallLogResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
+ (RecoverCallLogResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input;
+ (RecoverCallLogResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;
@end

@interface RecoverCallLogResponse_Builder : ES_PBGeneratedMessage_Builder {
@private
  RecoverCallLogResponse* result;
}

- (RecoverCallLogResponse*) defaultInstance;

- (RecoverCallLogResponse_Builder*) clear;
- (RecoverCallLogResponse_Builder*) clone;

- (RecoverCallLogResponse*) build;
- (RecoverCallLogResponse*) buildPartial;

- (RecoverCallLogResponse_Builder*) mergeFrom:(RecoverCallLogResponse*) other;
- (RecoverCallLogResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input;
- (RecoverCallLogResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry;

- (ES_PBAppendableArray *)callLog;
- (CallLog*)callLogAtIndex:(NSUInteger)index;
- (RecoverCallLogResponse_Builder *)addCallLog:(CallLog*)value;
- (RecoverCallLogResponse_Builder *)setCallLogArray:(NSArray *)array;
- (RecoverCallLogResponse_Builder *)setCallLogValues:(const CallLog* *)values count:(NSUInteger)count;
- (RecoverCallLogResponse_Builder *)clearCallLog;
@end

