// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Upload_contact_info_proto.pb.h"

@implementation UploadContactInfoProtoRoot
static ES_PBExtensionRegistry* extensionRegistry = nil;
+ (ES_PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UploadContactInfoProtoRoot class]) {
    ES_PBMutableExtensionRegistry* registry = [ES_PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [ContactProtoRoot registerAllExtensions:registry];
    [SyncUploadContactProtoRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(ES_PBMutableExtensionRegistry*) registry {
}
@end

@interface UploadContactInfoRequest ()
@property (retain) ES_PBAppendableArray * contactInfoArray;
@property (retain) ES_PBAppendableArray * groupInfoArray;
@property (retain) Contact* businessCard;
@end

@implementation UploadContactInfoRequest

@synthesize contactInfoArray;
@dynamic contactInfo;
@synthesize groupInfoArray;
@dynamic groupInfo;
- (BOOL) hasBusinessCard {
  return !!hasBusinessCard_;
}
- (void) setHasBusinessCard:(BOOL) value_ {
  hasBusinessCard_ = !!value_;
}
@synthesize businessCard;
- (void) dealloc {
  self.contactInfoArray = nil;
  self.groupInfoArray = nil;
  self.businessCard = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.businessCard = [Contact defaultInstance];
  }
  return self;
}
static UploadContactInfoRequest* defaultUploadContactInfoRequestInstance = nil;
+ (void) initialize {
  if (self == [UploadContactInfoRequest class]) {
    defaultUploadContactInfoRequestInstance = [[UploadContactInfoRequest alloc] init];
  }
}
+ (UploadContactInfoRequest*) defaultInstance {
  return defaultUploadContactInfoRequestInstance;
}
- (UploadContactInfoRequest*) defaultInstance {
  return defaultUploadContactInfoRequestInstance;
}
- (ES_PBArray *)contactInfo {
  return contactInfoArray;
}
- (Contact*)contactInfoAtIndex:(NSUInteger)index {
  return [contactInfoArray objectAtIndex:index];
}
- (ES_PBArray *)groupInfo {
  return groupInfoArray;
}
- (Group*)groupInfoAtIndex:(NSUInteger)index {
  return [groupInfoArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output {
  for (Contact *element in self.contactInfoArray) {
    [output writeMessage:1 value:element];
  }
  for (Group *element in self.groupInfoArray) {
    [output writeMessage:2 value:element];
  }
  if (self.hasBusinessCard) {
    [output writeMessage:3 value:self.businessCard];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  for (Contact *element in self.contactInfoArray) {
    size_ += ES_computeMessageSize(1, element);
  }
  for (Group *element in self.groupInfoArray) {
    size_ += ES_computeMessageSize(2, element);
  }
  if (self.hasBusinessCard) {
    size_ += ES_computeMessageSize(3, self.businessCard);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UploadContactInfoRequest*) parseFromData:(NSData*) data {
  return (UploadContactInfoRequest*)[[[UploadContactInfoRequest builder] mergeFromData:data] build];
}
+ (UploadContactInfoRequest*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadContactInfoRequest*)[[[UploadContactInfoRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UploadContactInfoRequest*) parseFromInputStream:(NSInputStream*) input {
  return (UploadContactInfoRequest*)[[[UploadContactInfoRequest builder] mergeFromInputStream:input] build];
}
+ (UploadContactInfoRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadContactInfoRequest*)[[[UploadContactInfoRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UploadContactInfoRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return (UploadContactInfoRequest*)[[[UploadContactInfoRequest builder] mergeFromCodedInputStream:input] build];
}
+ (UploadContactInfoRequest*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadContactInfoRequest*)[[[UploadContactInfoRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UploadContactInfoRequest_Builder*) builder {
  return [[[UploadContactInfoRequest_Builder alloc] init] autorelease];
}
+ (UploadContactInfoRequest_Builder*) builderWithPrototype:(UploadContactInfoRequest*) prototype {
  return [[UploadContactInfoRequest builder] mergeFrom:prototype];
}
- (UploadContactInfoRequest_Builder*) builder {
  return [UploadContactInfoRequest builder];
}
- (UploadContactInfoRequest_Builder*) toBuilder {
  return [UploadContactInfoRequest builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  for (Contact* element in self.contactInfoArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"contactInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  for (Group* element in self.groupInfoArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"groupInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasBusinessCard) {
    [output appendFormat:@"%@%@ {\n", indent, @"businessCard"];
    [self.businessCard writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UploadContactInfoRequest class]]) {
    return NO;
  }
  UploadContactInfoRequest *otherMessage = other;
  return
      [self.contactInfoArray isEqualToArray:otherMessage.contactInfoArray] &&
      [self.groupInfoArray isEqualToArray:otherMessage.groupInfoArray] &&
      self.hasBusinessCard == otherMessage.hasBusinessCard &&
      (!self.hasBusinessCard || [self.businessCard isEqual:otherMessage.businessCard]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  for (Contact* element in self.contactInfoArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  for (Group* element in self.groupInfoArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  if (self.hasBusinessCard) {
    hashCode = hashCode * 31 + [self.businessCard hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UploadContactInfoRequest_Builder()
@property (retain) UploadContactInfoRequest* result;
@end

@implementation UploadContactInfoRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[UploadContactInfoRequest alloc] init] autorelease];
  }
  return self;
}
- (ES_PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UploadContactInfoRequest_Builder*) clear {
  self.result = [[[UploadContactInfoRequest alloc] init] autorelease];
  return self;
}
- (UploadContactInfoRequest_Builder*) clone {
  return [UploadContactInfoRequest builderWithPrototype:result];
}
- (UploadContactInfoRequest*) defaultInstance {
  return [UploadContactInfoRequest defaultInstance];
}
- (UploadContactInfoRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UploadContactInfoRequest*) buildPartial {
  UploadContactInfoRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (UploadContactInfoRequest_Builder*) mergeFrom:(UploadContactInfoRequest*) other {
  if (other == [UploadContactInfoRequest defaultInstance]) {
    return self;
  }
  if (other.contactInfoArray.count > 0) {
    if (result.contactInfoArray == nil) {
      result.contactInfoArray = [[other.contactInfoArray copyWithZone:[other.contactInfoArray zone]] autorelease];
    } else {
      [result.contactInfoArray appendArray:other.contactInfoArray];
    }
  }
  if (other.groupInfoArray.count > 0) {
    if (result.groupInfoArray == nil) {
      result.groupInfoArray = [[other.groupInfoArray copyWithZone:[other.groupInfoArray zone]] autorelease];
    } else {
      [result.groupInfoArray appendArray:other.groupInfoArray];
    }
  }
  if (other.hasBusinessCard) {
    [self mergeBusinessCard:other.businessCard];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UploadContactInfoRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[ES_PBExtensionRegistry emptyRegistry]];
}
- (UploadContactInfoRequest_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  ES_PBUnknownFieldSet_Builder* unknownFields = [ES_PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        Contact_Builder* subBuilder = [Contact builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addContactInfo:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        Group_Builder* subBuilder = [Group builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addGroupInfo:[subBuilder buildPartial]];
        break;
      }
      case 26: {
        Contact_Builder* subBuilder = [Contact builder];
        if (self.hasBusinessCard) {
          [subBuilder mergeFrom:self.businessCard];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setBusinessCard:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (ES_PBAppendableArray *)contactInfo {
  return result.contactInfoArray;
}
- (Contact*)contactInfoAtIndex:(NSUInteger)index {
  return [result contactInfoAtIndex:index];
}
- (UploadContactInfoRequest_Builder *)addContactInfo:(Contact*)value {
  if (result.contactInfoArray == nil) {
    result.contactInfoArray = [ES_PBAppendableArray arrayWithValueType:ES_PBArrayValueTypeObject];
  }
  [result.contactInfoArray addObject:value];
  return self;
}
- (UploadContactInfoRequest_Builder *)setContactInfoArray:(NSArray *)array {
  result.contactInfoArray = [ES_PBAppendableArray arrayWithArray:array valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoRequest_Builder *)setContactInfoValues:(const Contact* *)values count:(NSUInteger)count {
  result.contactInfoArray = [ES_PBAppendableArray arrayWithValues:values count:count valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoRequest_Builder *)clearContactInfo {
  result.contactInfoArray = nil;
  return self;
}
- (ES_PBAppendableArray *)groupInfo {
  return result.groupInfoArray;
}
- (Group*)groupInfoAtIndex:(NSUInteger)index {
  return [result groupInfoAtIndex:index];
}
- (UploadContactInfoRequest_Builder *)addGroupInfo:(Group*)value {
  if (result.groupInfoArray == nil) {
    result.groupInfoArray = [ES_PBAppendableArray arrayWithValueType:ES_PBArrayValueTypeObject];
  }
  [result.groupInfoArray addObject:value];
  return self;
}
- (UploadContactInfoRequest_Builder *)setGroupInfoArray:(NSArray *)array {
  result.groupInfoArray = [ES_PBAppendableArray arrayWithArray:array valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoRequest_Builder *)setGroupInfoValues:(const Group* *)values count:(NSUInteger)count {
  result.groupInfoArray = [ES_PBAppendableArray arrayWithValues:values count:count valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoRequest_Builder *)clearGroupInfo {
  result.groupInfoArray = nil;
  return self;
}
- (BOOL) hasBusinessCard {
  return result.hasBusinessCard;
}
- (Contact*) businessCard {
  return result.businessCard;
}
- (UploadContactInfoRequest_Builder*) setBusinessCard:(Contact*) value {
  result.hasBusinessCard = YES;
  result.businessCard = value;
  return self;
}
- (UploadContactInfoRequest_Builder*) setBusinessCardBuilder:(Contact_Builder*) builderForValue {
  return [self setBusinessCard:[builderForValue build]];
}
- (UploadContactInfoRequest_Builder*) mergeBusinessCard:(Contact*) value {
  if (result.hasBusinessCard &&
      result.businessCard != [Contact defaultInstance]) {
    result.businessCard =
      [[[Contact builderWithPrototype:result.businessCard] mergeFrom:value] buildPartial];
  } else {
    result.businessCard = value;
  }
  result.hasBusinessCard = YES;
  return self;
}
- (UploadContactInfoRequest_Builder*) clearBusinessCard {
  result.hasBusinessCard = NO;
  result.businessCard = [Contact defaultInstance];
  return self;
}
@end

@interface UploadContactInfoResponse ()
@property (retain) NSString* sessionId;
@property int32_t contactListVersion;
@property (retain) ES_PBAppendableArray * contactMappingInfoArray;
@property (retain) ES_PBAppendableArray * groupMappingInfoArray;
@property int32_t businessCardVersion;
@end

@implementation UploadContactInfoResponse

- (BOOL) hasSessionId {
  return !!hasSessionId_;
}
- (void) setHasSessionId:(BOOL) value_ {
  hasSessionId_ = !!value_;
}
@synthesize sessionId;
- (BOOL) hasContactListVersion {
  return !!hasContactListVersion_;
}
- (void) setHasContactListVersion:(BOOL) value_ {
  hasContactListVersion_ = !!value_;
}
@synthesize contactListVersion;
@synthesize contactMappingInfoArray;
@dynamic contactMappingInfo;
@synthesize groupMappingInfoArray;
@dynamic groupMappingInfo;
- (BOOL) hasBusinessCardVersion {
  return !!hasBusinessCardVersion_;
}
- (void) setHasBusinessCardVersion:(BOOL) value_ {
  hasBusinessCardVersion_ = !!value_;
}
@synthesize businessCardVersion;
- (void) dealloc {
  self.sessionId = nil;
  self.contactMappingInfoArray = nil;
  self.groupMappingInfoArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sessionId = @"";
    self.contactListVersion = 0;
    self.businessCardVersion = 0;
  }
  return self;
}
static UploadContactInfoResponse* defaultUploadContactInfoResponseInstance = nil;
+ (void) initialize {
  if (self == [UploadContactInfoResponse class]) {
    defaultUploadContactInfoResponseInstance = [[UploadContactInfoResponse alloc] init];
  }
}
+ (UploadContactInfoResponse*) defaultInstance {
  return defaultUploadContactInfoResponseInstance;
}
- (UploadContactInfoResponse*) defaultInstance {
  return defaultUploadContactInfoResponseInstance;
}
- (ES_PBArray *)contactMappingInfo {
  return contactMappingInfoArray;
}
- (SyncMappingInfo*)contactMappingInfoAtIndex:(NSUInteger)index {
  return [contactMappingInfoArray objectAtIndex:index];
}
- (ES_PBArray *)groupMappingInfo {
  return groupMappingInfoArray;
}
- (SyncMappingInfo*)groupMappingInfoAtIndex:(NSUInteger)index {
  return [groupMappingInfoArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  for (SyncMappingInfo* element in self.contactMappingInfo) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  for (SyncMappingInfo* element in self.groupMappingInfo) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(ES_PBCodedOutputStream*) output {
  if (self.hasSessionId) {
    [output writeString:1 value:self.sessionId];
  }
  if (self.hasContactListVersion) {
    [output writeInt32:2 value:self.contactListVersion];
  }
  for (SyncMappingInfo *element in self.contactMappingInfoArray) {
    [output writeMessage:3 value:element];
  }
  for (SyncMappingInfo *element in self.groupMappingInfoArray) {
    [output writeMessage:4 value:element];
  }
  if (self.hasBusinessCardVersion) {
    [output writeInt32:5 value:self.businessCardVersion];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSessionId) {
    size_ += ES_computeStringSize(1, self.sessionId);
  }
  if (self.hasContactListVersion) {
    size_ += ES_computeInt32Size(2, self.contactListVersion);
  }
  for (SyncMappingInfo *element in self.contactMappingInfoArray) {
    size_ += ES_computeMessageSize(3, element);
  }
  for (SyncMappingInfo *element in self.groupMappingInfoArray) {
    size_ += ES_computeMessageSize(4, element);
  }
  if (self.hasBusinessCardVersion) {
    size_ += ES_computeInt32Size(5, self.businessCardVersion);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UploadContactInfoResponse*) parseFromData:(NSData*) data {
  return (UploadContactInfoResponse*)[[[UploadContactInfoResponse builder] mergeFromData:data] build];
}
+ (UploadContactInfoResponse*) parseFromData:(NSData*) data extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadContactInfoResponse*)[[[UploadContactInfoResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UploadContactInfoResponse*) parseFromInputStream:(NSInputStream*) input {
  return (UploadContactInfoResponse*)[[[UploadContactInfoResponse builder] mergeFromInputStream:input] build];
}
+ (UploadContactInfoResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadContactInfoResponse*)[[[UploadContactInfoResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UploadContactInfoResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return (UploadContactInfoResponse*)[[[UploadContactInfoResponse builder] mergeFromCodedInputStream:input] build];
}
+ (UploadContactInfoResponse*) parseFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  return (UploadContactInfoResponse*)[[[UploadContactInfoResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UploadContactInfoResponse_Builder*) builder {
  return [[[UploadContactInfoResponse_Builder alloc] init] autorelease];
}
+ (UploadContactInfoResponse_Builder*) builderWithPrototype:(UploadContactInfoResponse*) prototype {
  return [[UploadContactInfoResponse builder] mergeFrom:prototype];
}
- (UploadContactInfoResponse_Builder*) builder {
  return [UploadContactInfoResponse builder];
}
- (UploadContactInfoResponse_Builder*) toBuilder {
  return [UploadContactInfoResponse builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSessionId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"sessionId", self.sessionId];
  }
  if (self.hasContactListVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"contactListVersion", [NSNumber numberWithInt:self.contactListVersion]];
  }
  for (SyncMappingInfo* element in self.contactMappingInfoArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"contactMappingInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  for (SyncMappingInfo* element in self.groupMappingInfoArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"groupMappingInfo"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasBusinessCardVersion) {
    [output appendFormat:@"%@%@: %@\n", indent, @"businessCardVersion", [NSNumber numberWithInt:self.businessCardVersion]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UploadContactInfoResponse class]]) {
    return NO;
  }
  UploadContactInfoResponse *otherMessage = other;
  return
      self.hasSessionId == otherMessage.hasSessionId &&
      (!self.hasSessionId || [self.sessionId isEqual:otherMessage.sessionId]) &&
      self.hasContactListVersion == otherMessage.hasContactListVersion &&
      (!self.hasContactListVersion || self.contactListVersion == otherMessage.contactListVersion) &&
      [self.contactMappingInfoArray isEqualToArray:otherMessage.contactMappingInfoArray] &&
      [self.groupMappingInfoArray isEqualToArray:otherMessage.groupMappingInfoArray] &&
      self.hasBusinessCardVersion == otherMessage.hasBusinessCardVersion &&
      (!self.hasBusinessCardVersion || self.businessCardVersion == otherMessage.businessCardVersion) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasSessionId) {
    hashCode = hashCode * 31 + [self.sessionId hash];
  }
  if (self.hasContactListVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.contactListVersion] hash];
  }
  for (SyncMappingInfo* element in self.contactMappingInfoArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  for (SyncMappingInfo* element in self.groupMappingInfoArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  if (self.hasBusinessCardVersion) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.businessCardVersion] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UploadContactInfoResponse_Builder()
@property (retain) UploadContactInfoResponse* result;
@end

@implementation UploadContactInfoResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[UploadContactInfoResponse alloc] init] autorelease];
  }
  return self;
}
- (ES_PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UploadContactInfoResponse_Builder*) clear {
  self.result = [[[UploadContactInfoResponse alloc] init] autorelease];
  return self;
}
- (UploadContactInfoResponse_Builder*) clone {
  return [UploadContactInfoResponse builderWithPrototype:result];
}
- (UploadContactInfoResponse*) defaultInstance {
  return [UploadContactInfoResponse defaultInstance];
}
- (UploadContactInfoResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UploadContactInfoResponse*) buildPartial {
  UploadContactInfoResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (UploadContactInfoResponse_Builder*) mergeFrom:(UploadContactInfoResponse*) other {
  if (other == [UploadContactInfoResponse defaultInstance]) {
    return self;
  }
  if (other.hasSessionId) {
    [self setSessionId:other.sessionId];
  }
  if (other.hasContactListVersion) {
    [self setContactListVersion:other.contactListVersion];
  }
  if (other.contactMappingInfoArray.count > 0) {
    if (result.contactMappingInfoArray == nil) {
      result.contactMappingInfoArray = [[other.contactMappingInfoArray copyWithZone:[other.contactMappingInfoArray zone]] autorelease];
    } else {
      [result.contactMappingInfoArray appendArray:other.contactMappingInfoArray];
    }
  }
  if (other.groupMappingInfoArray.count > 0) {
    if (result.groupMappingInfoArray == nil) {
      result.groupMappingInfoArray = [[other.groupMappingInfoArray copyWithZone:[other.groupMappingInfoArray zone]] autorelease];
    } else {
      [result.groupMappingInfoArray appendArray:other.groupMappingInfoArray];
    }
  }
  if (other.hasBusinessCardVersion) {
    [self setBusinessCardVersion:other.businessCardVersion];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UploadContactInfoResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[ES_PBExtensionRegistry emptyRegistry]];
}
- (UploadContactInfoResponse_Builder*) mergeFromCodedInputStream:(ES_PBCodedInputStream*) input extensionRegistry:(ES_PBExtensionRegistry*) extensionRegistry {
  ES_PBUnknownFieldSet_Builder* unknownFields = [ES_PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setSessionId:[input readString]];
        break;
      }
      case 16: {
        [self setContactListVersion:[input readInt32]];
        break;
      }
      case 26: {
        SyncMappingInfo_Builder* subBuilder = [SyncMappingInfo builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addContactMappingInfo:[subBuilder buildPartial]];
        break;
      }
      case 34: {
        SyncMappingInfo_Builder* subBuilder = [SyncMappingInfo builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addGroupMappingInfo:[subBuilder buildPartial]];
        break;
      }
      case 40: {
        [self setBusinessCardVersion:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasSessionId {
  return result.hasSessionId;
}
- (NSString*) sessionId {
  return result.sessionId;
}
- (UploadContactInfoResponse_Builder*) setSessionId:(NSString*) value {
  result.hasSessionId = YES;
  result.sessionId = value;
  return self;
}
- (UploadContactInfoResponse_Builder*) clearSessionId {
  result.hasSessionId = NO;
  result.sessionId = @"";
  return self;
}
- (BOOL) hasContactListVersion {
  return result.hasContactListVersion;
}
- (int32_t) contactListVersion {
  return result.contactListVersion;
}
- (UploadContactInfoResponse_Builder*) setContactListVersion:(int32_t) value {
  result.hasContactListVersion = YES;
  result.contactListVersion = value;
  return self;
}
- (UploadContactInfoResponse_Builder*) clearContactListVersion {
  result.hasContactListVersion = NO;
  result.contactListVersion = 0;
  return self;
}
- (ES_PBAppendableArray *)contactMappingInfo {
  return result.contactMappingInfoArray;
}
- (SyncMappingInfo*)contactMappingInfoAtIndex:(NSUInteger)index {
  return [result contactMappingInfoAtIndex:index];
}
- (UploadContactInfoResponse_Builder *)addContactMappingInfo:(SyncMappingInfo*)value {
  if (result.contactMappingInfoArray == nil) {
    result.contactMappingInfoArray = [ES_PBAppendableArray arrayWithValueType:ES_PBArrayValueTypeObject];
  }
  [result.contactMappingInfoArray addObject:value];
  return self;
}
- (UploadContactInfoResponse_Builder *)setContactMappingInfoArray:(NSArray *)array {
  result.contactMappingInfoArray = [ES_PBAppendableArray arrayWithArray:array valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoResponse_Builder *)setContactMappingInfoValues:(const SyncMappingInfo* *)values count:(NSUInteger)count {
  result.contactMappingInfoArray = [ES_PBAppendableArray arrayWithValues:values count:count valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoResponse_Builder *)clearContactMappingInfo {
  result.contactMappingInfoArray = nil;
  return self;
}
- (ES_PBAppendableArray *)groupMappingInfo {
  return result.groupMappingInfoArray;
}
- (SyncMappingInfo*)groupMappingInfoAtIndex:(NSUInteger)index {
  return [result groupMappingInfoAtIndex:index];
}
- (UploadContactInfoResponse_Builder *)addGroupMappingInfo:(SyncMappingInfo*)value {
  if (result.groupMappingInfoArray == nil) {
    result.groupMappingInfoArray = [ES_PBAppendableArray arrayWithValueType:ES_PBArrayValueTypeObject];
  }
  [result.groupMappingInfoArray addObject:value];
  return self;
}
- (UploadContactInfoResponse_Builder *)setGroupMappingInfoArray:(NSArray *)array {
  result.groupMappingInfoArray = [ES_PBAppendableArray arrayWithArray:array valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoResponse_Builder *)setGroupMappingInfoValues:(const SyncMappingInfo* *)values count:(NSUInteger)count {
  result.groupMappingInfoArray = [ES_PBAppendableArray arrayWithValues:values count:count valueType:ES_PBArrayValueTypeObject];
  return self;
}
- (UploadContactInfoResponse_Builder *)clearGroupMappingInfo {
  result.groupMappingInfoArray = nil;
  return self;
}
- (BOOL) hasBusinessCardVersion {
  return result.hasBusinessCardVersion;
}
- (int32_t) businessCardVersion {
  return result.businessCardVersion;
}
- (UploadContactInfoResponse_Builder*) setBusinessCardVersion:(int32_t) value {
  result.hasBusinessCardVersion = YES;
  result.businessCardVersion = value;
  return self;
}
- (UploadContactInfoResponse_Builder*) clearBusinessCardVersion {
  result.hasBusinessCardVersion = NO;
  result.businessCardVersion = 0;
  return self;
}
@end

